/**
 * Which zones eqlwiki says are next to which — GENERATED, do not edit by hand.
 *
 * Regenerate with `node scripts/fetch-zone-adjacency.mjs`. Shipped rather than fetched, so a normal
 * launch costs the wiki nothing; re-run it when the wiki moves on.
 *
 * **A claim, not a measurement.** It says two zones connect and never where the crossing is, so a
 * border added from it has no position in either zone: every walk to it is priced by
 * `UNKNOWN_CROSSING` and flagged, which is the honest shape for something nobody drew. A border the
 * maps *did* draw is never overridden by it — an exact map label beats the wiki beats everything else
 * (see specs/travel).
 *
 * Names are the wiki's own, resolved against this pack's zones at build time by the same fold every
 * zone comparison in the app shares. Nothing should import this file directly — the lookup is
 * `adjacency.ts` beside it.
 *
 * 115 zones, 264 stated pairs.
 */

/** A zone name → the zones its page lists as adjacent, as the wiki spells them. */
export const WIKI_ADJACENT: Readonly<Record<string, readonly string[]>> = {
  "Ak'Anon": ["Steamfont Mountains"],
  "Befallen": ["West Commonlands"],
  "Blackburrow": ["Qeynos Hills", "Everfrost Peaks"],
  "Burning Wood": ["Frontier Mountains", "Dreadlands", "Skyfire Mountains", "Chardok"],
  "Butcherblock Mountains": ["Greater Faydark", "South Kaladim", "Dagnor's Cauldron", "Timorous Deep", "Ocean of Tears"],
  "Cabilis": ["Field of Bone", "Swamp of No Hope", "Lake of Ill Omen", "Warsliks Woods"],
  "Cazic Thule (Zone)": ["Feerrott"],
  "Chardok (Post-Revamp)": ["Burning Wood"],
  "Chardok (Pre-Revamp)": ["Burning Wood"],
  "City of Mist": ["Emerald Jungle"],
  "Cobalt Scar": ["Siren's Grotto", "Skyshrine"],
  "Crushbone": ["Greater Faydark"],
  "Crystal Caverns": ["Eastern Wastes"],
  "Dagnor's Cauldron": ["Butcherblock Mountains", "The Estate of Unrest", "Kedge Keep"],
  "Dalnir": ["Warsliks Woods"],
  "Dragon Necropolis": ["Western Wastes"],
  "Dreadlands": ["Burning Wood", "Frontier Mountains", "Firiona Vie", "Karnor's Castle"],
  "East Commonlands": ["West Commonlands", "Nektulos Forest", "Northern Desert of Ro", "West Freeport"],
  "Eastern Plains of Karana": ["Northern Plains of Karana", "Highpass Hold", "Gorge of King Xorbb"],
  "Eastern Wastes": ["Crystal Caverns", "Iceclad Ocean", "Great Divide", "Kael Drakkal", "Sleeper's Tomb"],
  "Emerald Jungle": ["City of Mist", "Field of Bone", "Trakanon's Teeth"],
  "Erud's Crossing": ["Erudin", "Qeynos"],
  "Erudin": ["Erud's Crossing", "Toxxulia Forest"],
  "Everfrost Peaks": ["Halas", "Blackburrow", "Permafrost"],
  "Felwithe": ["Greater Faydark"],
  "Field of Bone": ["East Cabilis", "Emerald Jungle", "Kaesora", "Kurn's Tower", "Swamp of No Hope", "Warsliks Wood"],
  "Firiona Vie": ["Dreadlands", "Lake of Ill Omen", "Swamp of No Hope", "Timorous Deep"],
  "Freeport": ["East Commonlands", "Northern Desert of Ro", "Ocean of Tears", "Plane of Sky"],
  "Frontier Mountains": ["Burning Wood", "Dreadlands", "Lake of Ill Omen", "The Overthere", "Mines of Nurga", "Temple of Droga"],
  "Gorge of King Xorbb": ["Eastern Plains of Karana", "Runnyeye"],
  "Great Divide": ["Eastern Wastes", "Thurgadin", "Velketor's Labyrinth"],
  "Greater Faydark": ["Felwithe", "Butcherblock Mountains", "Lesser Faydark", "Crushbone", "Kelethin"],
  "Grobb": ["Innothule Swamp"],
  "Halas": ["Everfrost Peaks"],
  "High Keep": ["Highpass Hold"],
  "Highpass Hold": ["Eastern Plains of Karana", "Kithicor Forest", "High Keep"],
  "Howling Stones": ["The Overthere"],
  "Iceclad Ocean": ["North Ro", "Eastern Wastes", "Tower of Frozen Shadow"],
  "Icewell Keep": ["Thurgadin"],
  "Innothule Swamp": ["Grobb", "Upper Guk", "Southern Desert of Ro", "The Feerrott"],
  "Kael Drakkel": ["Eastern Wastes", "Wakening Land"],
  "Kaesora": ["Field of Bone"],
  "Kaladim": ["Butcherblock Mountains"],
  "Karnor's Castle": ["Dreadlands"],
  "Kedge Keep": ["Dagnor's Cauldron"],
  "Kelethin": ["Greater Faydark"],
  "Kerra Island": ["Toxxulia Forest"],
  "Kithicor Forest": ["Rivervale", "West Commonlands", "Highpass Hold"],
  "Kurn's Tower": ["Field of Bone"],
  "Lake of Ill Omen": ["West Cabilis", "Firiona Vie", "Frontier Mountains", "Warsliks Woods"],
  "Lake Rathetear": ["Southern Plains of Karana", "The Arena", "Rathe Mountains"],
  "Lavastorm Mountains": ["The Temple of Solusek Ro", "Solusek's Eye", "Nagafen's Lair", "Najena", "Nektulos Forest"],
  "Lesser Faydark": ["Greater Faydark", "Steamfont Mountains", "Mistmoore Castle"],
  "Lower Guk": ["Upper Guk"],
  "Mines of Nurga": ["Frontier Mountains", "Temple of Droga"],
  "Mistmoore Castle": ["Lesser Faydark"],
  "Misty Thicket": ["Rivervale", "Runnyeye"],
  "Nagafen's Lair": ["Lavastorm Mountains", "Solusek's Eye"],
  "Najena": ["Lavastorm Mountains"],
  "Nektulos Forest": ["Neriak", "East Commonlands", "Lavastorm Mountains"],
  "Neriak": ["Nektulos Forest"],
  "New Sebilis Expedition": ["The Northern Desert of Ro"],
  "Northern Plains of Karana": ["Western Plains of Karana", "Eastern Plains of Karana", "Southern Plains of Karana"],
  "Oasis of Marr": ["Northern Desert of Ro", "Southern Desert of Ro", "Plane of Hate", "Timorous Deep"],
  "Ocean of Tears": ["East Freeport", "Butcherblock Mountains"],
  "Oggok": ["Feerrott"],
  "Old Sebilis": ["Trakanon's Teeth"],
  "Paineel": ["The Hole", "The Warrens", "Toxxulia Forest"],
  "Permafrost": ["Everfrost Peaks"],
  "Plane of Fear": ["The Feerrott"],
  "Plane of Growth": ["The Wakening Land"],
  "Plane of Hate": ["Wizard", "Oasis of Marr"],
  "Plane of Mischief": ["Temple of Veeshan", "Cobalt Scar"],
  "Plane of Sky": ["East Freeport", "Wizard"],
  "Qeynos": ["Erud's Crossing", "Qeynos Aqueducts", "Qeynos Hills"],
  "Qeynos Aqueducts": ["Qeynos"],
  "Qeynos Hills": ["North Qeynos", "Blackburrow", "Western Plains of Karana", "Surefall Glade"],
  "Rathe Mountains": ["Lake Rathetear", "The Feerrott"],
  "Rivervale": ["Kithicor Forest", "Misty Thicket"],
  "Runnyeye": ["Misty Thicket", "Gorge of King Xorbb"],
  "Siren's Grotto": ["Cobalt Scar", "Western Wastes"],
  "Skyfire Mountains": ["Burning Wood", "The Overthere", "Veeshan's Peak"],
  "Skyshrine": ["Cobalt Scar", "The Wakening Land"],
  "Sleeper's Tomb": ["Eastern Wastes"],
  "Solusek's Eye": ["Nagafen's Lair", "Lavastorm Mountains"],
  "Southern Desert of Ro": ["Innothule Swamp", "Oasis of Marr"],
  "Southern Karana": ["Northern Plains of Karana", "Lake Rathetear", "Splitpaw Lair"],
  "Splitpaw Lair": ["Southern Plains of Karana"],
  "Steamfont Mountains": ["Lesser Faydark", "Ak'Anon"],
  "Stonebrunt Mountains": ["The Warrens"],
  "Surefall Glade": ["Qeynos Hills"],
  "Swamp of No Hope": ["East Cabilis", "Field of Bone", "Firiona Vie", "Trakanon's Teeth"],
  "Temple of Droga": ["Mines of Nurga", "Frontier Mountains"],
  "Temple of Veeshan": ["Plane of Mischief", "Western Wastes"],
  "The Arena": ["Lake Rathetear"],
  "The Estate of Unrest": ["Dagnor's Cauldron"],
  "The Feerrott": ["Rathe Mountains", "Oggok", "Cazic Thule", "Plane of Fear", "Innothule Swamp"],
  "The Hole": ["Paineel", "Neriak Third Gate", "Erudin"],
  "The Northern Desert of Ro": ["East Freeport", "East Commonlands", "Iceclad Ocean", "Oasis of Marr", "New Sebilis Expedition"],
  "The Overthere": ["Frontier Mountains", "Howling Stones", "Skyfire Mountains", "Timorous Deep", "Warsliks Woods"],
  "The Temple of Solusek Ro": ["Lavastorm Mountains"],
  "The Wakening Land": ["Kael Drakkal", "Plane of Growth", "Skyshrine"],
  "The Warrens": ["Paineel", "Stonebrunt Mountains"],
  "Thurgadin": ["The Great Divide", "Icewell Keep"],
  "Timorous Deep": ["Butcherblock Mountains", "Firiona Vie", "Oasis of Marr", "The Overthere"],
  "Tower of Frozen Shadow": ["Iceclad Ocean"],
  "Toxxulia Forest": ["Kerra Island", "Erudin", "Paineel"],
  "Trakanon's Teeth": ["Emerald Jungle", "Swamp of No Hope", "Sebilis"],
  "Upper Guk": ["Innothule Swamp", "Lower Guk"],
  "Veeshan's Peak": ["Skyfire Mountains"],
  "Velketor's Labyrinth": ["Great Divide"],
  "Warsliks Woods": ["Dalnir", "Field of Bone", "Lake of Ill Omen", "The Overthere", "West Cabilis"],
  "West Commonlands": ["East Commonlands", "Kithicor Forest", "Befallen"],
  "Western Karana": ["Qeynos Hills", "Northern Plains of Karana"],
  "Western Wastes": ["Dragon Necropolis", "Siren's Grotto", "Temple of Veeshan"],
};
