/**
 * Which expansion each EverQuest zone came with — GENERATED, do not edit by hand.
 *
 * Regenerate with `node scripts/fetch-zone-expansions.mjs`, which fetches each expansion's own zone
 * table from the EverQuest fandom wiki and refuses to write if it would file a zone **this server
 * knows** under an expansion the server doesn't run. Base zones only: a mission or raid instance has
 * no map file of its own.
 *
 * Ordered by release, so "past the era" can be read off the table. Where two expansions list the same
 * zone (a revamp), the **earliest** owns it — what matters is when the zone first existed.
 *
 * The lookup over this, and the policy about which expansions this server runs, are hand-written in
 * `expansions.ts` beside it. Nothing should import this file directly.
 *
 * 351 zones across 22 expansions.
 */

export interface ExpansionZones {
  /** As the fandom wiki names it, without the "EverQuest: " prefix. */
  expansion: string;
  /** Release date, verbatim from the expansion's infobox. */
  released: string;
  zones: string[];
}

export const ZONE_EXPANSIONS: ExpansionZones[] = [
  {
    expansion: "Original Release",
    released: "March 16, 1999",
    zones: [
      "Ak'Anon",
      "Befallen",
      "Blackburrow",
      "Castle Mistmoore",
      "Clan Runnyeye",
      "Commonlands",
      "Crushbone",
      "Dagnor's Cauldron",
      "East Karana",
      "Erud's Crossing",
      "Erudin",
      "Erudin Palace",
      "Estate of Unrest",
      "Everfrost Peaks",
      "Felwithe",
      "Freeport",
      "Freeport Sewers",
      "Gorge of King Xorbb",
      "Greater Faydark",
      "Grobb",
      "Halas",
      "High Keep",
      "Highpass Hold",
      "Infected Paw",
      "Innothule Swamp",
      "Kaladim",
      "Kedge Keep",
      "Kithicor Forest",
      "Lake Rathetear",
      "Lavastorm Mountains",
      "Lesser Faydark",
      "Lower Guk",
      "Misty Thicket",
      "Nagafen's Lair",
      "Najena",
      "Nektulos Forest",
      "Neriak",
      "North Karana",
      "North Ro",
      "Ocean of Tears",
      "Oggok",
      "Paineel",
      "Permafrost Keep",
      "Plane of Fear",
      "Plane of Hate",
      "Plane of Sky",
      "Qeynos",
      "Qeynos Catacombs",
      "Qeynos Hills",
      "Rathe Mountains",
      "Rivervale",
      "Solusek's Eye",
      "South Karana",
      "South Ro",
      "Steamfont Mountains",
      "Surefall Glade",
      "Temple of Cazic-Thule",
      "Temple of Solusek Ro",
      "The Feerrott",
      "Toxxulia Forest",
      "Upper Guk",
      "West Karana",
    ],
  },
  {
    expansion: "The Ruins of Kunark",
    released: "April 24, 2000",
    zones: [
      "Burning Woods",
      "Cabilis",
      "Chardok",
      "City of Mist",
      "Dalnir",
      "Dreadlands",
      "Emerald Jungle",
      "Field of Bone",
      "Firiona Vie",
      "Frontier Mountains",
      "Howling Stones",
      "Kaesora",
      "Karnor's Castle",
      "Kurn's Tower",
      "Lake of Ill Omen",
      "Mines of Nurga",
      "Old Sebilis",
      "Skyfire Mountains",
      "Swamp of No Hope",
      "Temple of Droga",
      "The Hole",
      "Timorous Deep",
      "Trakanon's Teeth",
      "Veeshan's Peak",
      "Warsliks Wood",
    ],
  },
  {
    expansion: "The Scars of Velious",
    released: "December 5, 2000",
    zones: [
      "Cobalt Scar",
      "Crystal Caverns",
      "Dragon Necropolis",
      "Eastern Wastes",
      "Iceclad Ocean",
      "Icewell Keep",
      "Kael Drakkal",
      "Plane of Growth",
      "Plane of Mischief",
      "Siren's Grotto",
      "Skyshrine",
      "Sleeper's Tomb",
      "Stonebrunt Mountains",
      "Temple of Veeshan",
      "The Warrens",
      "Thurgadin",
      "Tower of Frozen Shadow",
      "Velketor's Labyrinth",
      "Wakening Land",
      "Western Wastes",
    ],
  },
  {
    expansion: "The Shadows of Luclin",
    released: "December 4, 2001",
    zones: [
      "Acrylia Caverns",
      "Akheva Ruins",
      "Dawnshroud Peaks",
      "Echo Caverns",
      "Fungus Grove",
      "Grieg's End",
      "Grimling Forest",
      "Hollowshade Moor",
      "Katta Castellum",
      "Maiden's Eye",
      "Marus Seru",
      "Mons Letalis",
      "Netherbian Lair",
      "Paludal Caverns",
      "Sanctus Seru",
      "Scarlet Desert",
      "Shadeweaver's Thicket",
      "Shadow Haven",
      "Shar Vahl",
      "Ssraeshza Temple",
      "Tenebrous Mountains",
      "The Bazaar",
      "The Deep",
      "The Grey",
      "The Nexus",
      "Twilight Sea",
      "Umbral Plains",
      "Vex Thal",
    ],
  },
  {
    expansion: "The Planes of Power",
    released: "October 29, 2002",
    zones: [
      "Doomfire, the Burning Lands (Plane of Fire)",
      "Drunder, Fortress of Zek (Plane of Tactics)",
      "Eryslai, the Kingdom of Wind (Plane of Air)",
      "Halls of Honor",
      "Lair of Terris Thule",
      "Plane of Disease",
      "Plane of Innovation",
      "Plane of Justice",
      "Plane of Knowledge",
      "Plane of Nightmare",
      "Plane of Storms",
      "Plane of Time A",
      "Plane of Time B",
      "Plane of Torment",
      "Plane of Tranquility",
      "Plane of Valor",
      "Plane of War",
      "Ragrax, Stronghold of the Twelve",
      "Reef of Coirnav (Plane of Water)",
      "Ruins of Lxanvom (Crypt of Decay)",
      "Solusek Ro's Tower",
      "Temple of Marr",
      "Torden, the Bastion of Thunder",
      "Vegarlson, the Earthen Badlands (Plane of Earth)",
    ],
  },
  {
    expansion: "Legacy of Ykesha",
    released: "February 25, 2003",
    zones: [
      "Crypt of Nadox",
      "Dulak's Harbor",
      "Gulf of Gunthak",
      "Hate's Fury, The Scorned Maiden",
      "Torgiran Mines",
    ],
  },
  {
    expansion: "Lost Dungeons of Norrath",
    released: "September 9, 2003",
    zones: [
      "Deepest Guk",
      "Miragul's Menagerie",
      "Mistmoore Catacombs",
      "Rujarkin Hills",
      "Takish-Hiz",
    ],
  },
  {
    expansion: "Gates of Discord",
    released: "February 9, 2004",
    zones: [
      "Abysmal Sea",
      "Barindu, Hanging Gardens",
      "Ferubi, Forgotten Temple of Taelosia",
      "Inku'Ta, The Unmasked Chapel",
      "Kod'Taz, Broken Trial Grounds",
      "Natimbi, The Broken Shores",
      "Qinimi, Court of Nihilia",
      "Qvic, Prayer Grounds of Calling",
      "Riwwi, Coliseum of Games",
      "Sewers of Nihilia, Lair of Trapped Ones",
      "Sewers of Nihilia, Pool of Sludge",
      "Sewers of Nihilia, Purifying Plant",
      "Sewers of Nihilia, the Crematory",
      "Tacvi, Seat of the Slaver",
      "Tipt, Treacherous Crags",
      "Txevu, Lair of the Elite",
      "Uqua, The Ocean God Chantry",
      "Vixed, The Crumbling Caverns",
      "Yxtta, Pulpit of Exiles",
    ],
  },
  {
    expansion: "Dragons of Norrath",
    released: "February 15, 2005",
    zones: [
      "Guild Hall",
      "Guild Lobby",
      "Lavaspinner's Lair",
      "Stillmoon Temple",
      "The Accursed Nest",
      "The Ascent",
      "The Broodlands",
      "Thundercrest Isles",
      "Tirranun's Delve",
    ],
  },
  {
    expansion: "Depths of Darkhollow",
    released: "September 13, 2005",
    zones: [
      "Caverns of the Lost",
      "Corathus Creep",
      "Dreadspire Keep",
      "Illsalin Marketplace",
      "Lair of the Creep Beast",
      "Lodge of the Fang",
      "Queen Sendaii's Lair",
      "Ruins of Illsalin",
      "Shadow Spine",
      "Stoneroot Falls",
      "The Hive",
      "The Liberation of Runnyeye",
      "Undershore",
    ],
  },
  {
    expansion: "Prophecy of Ro",
    released: "February 21, 2006",
    zones: [
      "Academy of Arcane Sciences",
      "Arcstone, Isle of Spirits",
      "Deathknell, Tower of Dissonance",
      "Freeport Arena",
      "Freeport Militia House",
      "Freeport Sewers",
      "Hall of Truth",
      "Razorthorn, Tower of Sullon Zek",
      "Relic, the Artifact City",
      "Ruins of Takish-Hiz",
      "Sverag, Stronghold of Rage",
      "The Devastation",
      "The Elddar Forest",
      "The Seething Wall",
      "Theater of Blood",
      "Theater of the Tranquil",
    ],
  },
  {
    expansion: "The Serpent's Spine",
    released: "September 19, 2006",
    zones: [
      "Ashengate East",
      "Ashengate North",
      "Ashengate West",
      "Ashengate, Reliquary of the Scale",
      "Blackfeather Roost",
      "Blightfire Moors",
      "Crescent Reach",
      "Direwind Cliffs",
      "Frostcrypt, Throne of the Shade King",
      "Goru'kar Mesa",
      "Icefall Glacier",
      "Stone Hive",
      "Sunderock Springs",
      "The Steppes",
      "Valdeholm",
      "Vergalid Mines",
    ],
  },
  {
    expansion: "The Buried Sea",
    released: "February 13, 2007",
    zones: [
      "Barren Coast",
      "Jewel of Atiiki",
      "Katta Castrum",
      "Silyssar, New Chelsith",
      "Solteris, the Throne of Ro",
      "Thalassius, the Coral Keep",
      "The Buried Sea",
      "Zhisza, the Shissar Sanctuary",
    ],
  },
  {
    expansion: "Secrets of Faydwer",
    released: "November 13, 2007",
    zones: [
      "Bloodmoon Keep",
      "Crypt of Shade",
      "Crystallos, Lair of the Awakened",
      "Deepscar's Den",
      "Dragonscale Hills",
      "Fortress Mechanotus",
      "Gyrospire Beza",
      "Gyrospire Zeka",
      "Hills of Shade",
      "Loping Plains",
      "Meldrath's Majestic Mansion",
      "S.H.I.P Workshop",
      "Sandkeep Endurance Raid",
      "The Steam Factory",
    ],
  },
  {
    expansion: "Seeds of Destruction",
    released: "October 21, 2008",
    zones: [
      "Bloody Kithicor",
      "Citadel of the Worldslayer",
      "City of Dranik",
      "Field of Scale",
      "Kaesora Hatchery",
      "Kaesora Library",
      "Korafax, Home of the Riders",
      "Korascian Warrens",
      "Oceangreen Hills",
      "Oceangreen Village",
      "Old Blackburrow",
      "Old Bloodfields",
      "Old Commonlands",
      "Old Kurn's Tower",
      "Rathe Council Chambers",
      "Temple of Bertoxxulous",
      "The Precipice of War{{!}}The&nbsp;Precipice of War",
      "The Void \"A\"",
      "The Void \"B\"",
      "The Void \"C\"",
      "The Void \"D\"",
      "The Void \"E\"",
      "The Void \"F\"",
      "The Void \"G\"",
      "Toskirakk",
    ],
  },
  {
    expansion: "Underfoot",
    released: "December 15, 2009",
    zones: [
      "Arthicrex",
      "Arthicrex To Serve Sporali",
      "Brell's Arena",
      "Brell's Rest",
      "Brell's Temple",
      "Convorteum",
      "Cooling Chamber",
      "Fungal Forest",
      "Kernagir, the Shining City",
      "Lichen Creep",
      "Pellucid Grotto",
      "The Foundation",
      "The Underquarry",
      "Volska's Husk",
    ],
  },
  {
    expansion: "House of Thule",
    released: "October 12, 2010",
    zones: [
      "Al'Kabor's Nightmare",
      "Erudin Burning",
      "Fear Itself",
      "Feerrott, the Dream",
      "House of Thule, Lower Floors",
      "House of Thule, Upper Floors",
      "Miragul's Nightmare",
      "Miragul's Phylactery",
      "Morell's Castle",
      "Sanctum Somnium",
      "Sunrise Hills",
      "The Grounds",
      "The Library",
      "The Well",
    ],
  },
  {
    expansion: "Veil of Alaris",
    released: "November 15, 2011",
    zones: [
      "Argath, Bastion of Illdaera",
      "Beasts' Domain",
      "Erillion, City of Bronze",
      "Pillars of Alra",
      "Resplendent Temple",
      "Rubak Oseka, Temple of the Sea",
      "Sarith, City of Tides",
      "Sepulcher East",
      "Sepulcher West",
      "Sepulcher of Order",
      "Valley of Lunanyn",
      "Windsong Sanctuary",
    ],
  },
  {
    expansion: "Rain of Fear",
    released: "November 28, 2012",
    zones: [
      "Breeding Grounds",
      "Chapterhouse of the Fallen",
      "Corrupted Temple of Veeshan",
      "Evantil, the Vile Oak",
      "Grelleth's Palace, Chateau of Filth",
      "Kael Drakkel, The King's Madness",
      "Shard's Landing",
      "Valley of King Xorbb",
    ],
  },
  {
    expansion: "Call of the Forsaken",
    released: "October 8, 2013",
    zones: [
      "Bixie Warfront",
      "Dead Hills",
      "Ethernere Tainted West Karana",
      "Neriak Fourth Gate",
      "The Void \"H\"",
    ],
  },
  {
    expansion: "Empires of Kunark",
    released: "November 16, 2016",
    zones: [
      "Chardok (Empires of Kunark)",
      "Frontier Mountains (Empires of Kunark)",
      "Gates of Kor-Sha",
      "Kor-Sha Laboratory",
      "Lceanium",
      "Scorched Woods",
      "Temple of Droga (Empires of Kunark)",
    ],
  },
  {
    expansion: "The Broken Mirror",
    released: "November 21st, 2015",
    zones: [
      "Crypt of Sul",
      "Plane of Health",
      "Ruins of Lxanvom",
    ],
  },
];
