/**
 * Which expansion a zone came with, and therefore whether it exists on this server.
 *
 * **The problem this solves.** A map pack surveys EverQuest, not EQ Legends: Brewall's draws all 26
 * expansions, so the app is handed maps for Argath, Bastion of Illdaera and exit labels pointing at
 * them. Left alone, those become zones you can pick, routes you can be sent along, and a travel graph
 * with a Veil of Alaris shortcut through it. Nothing in the map corpus can tell them apart — a `.txt`
 * of Argath looks exactly like a `.txt` of Greater Faydark.
 *
 * **Two sources, because they answer different questions.**
 *
 *  - `ZONE_EXPANSIONS` (generated by `scripts/fetch-zone-expansions.mjs` from the EverQuest fandom
 *    wiki) says **when a zone first existed** — a fact about EverQuest that never changes. That's what
 *    rules out everything past this server's era, including the expansions eqlwiki has never heard of.
 *  - eqlwiki's live era flags say **which of the eras the server does know are open right now**, which
 *    changes as the server progresses. That's `WikiClient.outOfEraZones`, passed in as `outOfEra`.
 *
 * **It fails open, deliberately.** A zone the table has never heard of is `"unknown"` and treated as
 * available. Excluding a zone the server *has* would cut it out of the map and every route silently,
 * which is far worse than offering one it hasn't — and there are real zones in that gap: Legends' own
 * custom zones, and the 26 zones eqlwiki names differently from fandom ("Kerra Island" for "Kerra
 * Isle", "Eastern Plains of Karana" for "East Karana"). The generator refuses to write a table that
 * would misfile a zone eqlwiki knows, which is the other half of that guarantee.
 *
 * Pure and dependency-free apart from the shared zone fold. See
 * [ADR 0065](../../../specs/decisions/0065-a-zone-belongs-to-an-expansion.md).
 */

import { zoneKey } from "../names";
import { ZONE_EXPANSIONS } from "./expansions.generated";
import { createZoneResolver } from "./resolve";

export type { ExpansionZones } from "./expansions.generated";
export { ZONE_EXPANSIONS };

/**
 * The expansions EQ Legends runs.
 *
 * Kunark and Velious are here even though they're currently **out of era**: the server *has* them, and
 * whether they're open right now is eqlwiki's business, not this table's. Keeping the two apart is what
 * lets an era opening need no code change.
 */
export const SERVER_EXPANSIONS: readonly string[] = [
  "Original Release",
  "The Ruins of Kunark",
  "The Scars of Velious",
];

/** What a zone is: which expansion added it, and when that shipped. */
export interface ZoneExpansion {
  /** The zone's name as the expansion table has it — not necessarily how a map pack labels it. */
  zone: string;
  expansion: string;
  released: string;
  /** Does this server run that expansion at all? */
  onServer: boolean;
}

/**
 * Zone → expansion, folded. Built once: a few hundred zones is small, and every caller asks by name.
 *
 * Earliest expansion wins where two list the same zone, which the generated table already guarantees by
 * being release-ordered — a revamp doesn't change when a zone came into existence.
 */
const byZone = ((): Map<string, ZoneExpansion> => {
  const map = new Map<string, ZoneExpansion>();
  const onServer = new Set(SERVER_EXPANSIONS);
  for (const { expansion, released, zones } of ZONE_EXPANSIONS) {
    for (const zone of zones) {
      const key = zoneKey(zone);
      if (key && !map.has(key)) map.set(key, { zone, expansion, released, onServer: onServer.has(expansion) });
    }
  }
  return map;
})();

/**
 * Which expansion a zone came with, or `undefined` if the table has never heard of it.
 *
 * Matched through `zoneKey`, the app's one zone fold — so a difficulty ("Blackburrow 3"), a leading
 * "the", the backtick EverQuest writes for an apostrophe and a known alias all resolve.
 */
export function zoneExpansion(zone: string): ZoneExpansion | undefined {
  return look(zone).found;
}

/**
 * The table, asked loosely. This is the one lookup in the app that takes **every** tier the resolver
 * offers, because it is the one where a wrong answer is cheapest: the result is a badge and an
 * availability check that already fails open, so a zone matched to the wrong neighbour is mislabelled
 * rather than mis-drawn. The map and the router don't get that latitude — see
 * [ADR 0068](../../../specs/decisions/0068-a-zone-name-resolves-against-what-we-know.md).
 *
 * It earns its keep immediately: the app's own zone names and fandom's disagree for 16 of the 31
 * zones stated in `CURATED_ZONES`, and every one of those looked up as "unknown" before this.
 */
const resolver = createZoneResolver([...byZone.values()], (z) => z.zone, { narrow: true, fuzzy: true });

/**
 * The fold and the lookup, once, for the callers that want both. `zoneUnavailable` needs the key too
 * (for the era set) and used to fold the same name a second time to get it.
 */
function look(zone: string): { key: string; found?: ZoneExpansion } {
  const key = zoneKey(zone);
  return { key, found: key ? resolver.resolve(zone)?.item : undefined };
}

/**
 * Why a zone can't be gone to, or `undefined` when it can.
 *
 * - `"future"` — it belongs to an expansion this server doesn't run. Never changes.
 * - `"out-of-era"` — the server has the expansion but hasn't opened it yet. Changes when it does.
 *
 * `outOfEra` is the live list from eqlwiki; without it only the permanent answer is given, which is the
 * right way to fail when the wiki is unreachable.
 */
export type ZoneUnavailable = "future" | "out-of-era";

export function zoneUnavailable(zone: string, outOfEra?: ReadonlySet<string>): ZoneUnavailable | undefined {
  const { key, found } = look(zone);
  if (found && !found.onServer) return "future";
  // Checked second: an expansion the server doesn't have isn't merely "not open yet", and a zone the
  // table doesn't know can still be flagged by the wiki, which is the more specific source.
  if (key && outOfEra?.has(key)) return "out-of-era";
  return undefined;
}

/**
 * Can you go there? **True unless we can say otherwise** — see the note on failing open above.
 *
 * This is the one question the app asks: the map's zone list, the travel graph's exclusions and the
 * route panel all go through it, so they can't disagree about which world you're in.
 */
export function zoneAvailable(zone: string, outOfEra?: ReadonlySet<string>): boolean {
  return zoneUnavailable(zone, outOfEra) === undefined;
}

/** The live out-of-era list as a folded set, ready for the functions above. */
export function outOfEraSet(zones: Iterable<string>): ReadonlySet<string> {
  const set = new Set<string>();
  for (const zone of zones) {
    const key = zoneKey(zone);
    if (key) set.add(key);
  }
  return set;
}

/** How a zone's unavailability reads to a person. */
export function unavailableReason(why: ZoneUnavailable, found?: ZoneExpansion): string {
  if (why === "out-of-era") return "not in this era yet";
  return found ? `${found.expansion} — not on this server` : "not on this server";
}
