/**
 * What level a zone's monsters are, as eqlwiki states it — GENERATED, do not edit by hand.
 *
 * Regenerate with `node scripts/fetch-zone-levels.mjs`. Shipped rather than fetched, so a normal
 * launch costs the wiki nothing; re-run it when the wiki moves on.
 *
 * **Verbatim, because a zone is not one span.** `1-20, 35` and `29-34 Droga Main, 33-38 Inner
 * Sanctum` are two bands and a note about where each one is, and the min-and-max they'd collapse to
 * would be a claim the wiki never made. So the value is the wiki's own wording, shown as written —
 * the same choice `levels.ts` makes for a mob, one level up
 * ([ADR 0122](../../../specs/decisions/0122-a-zone-wears-its-levels.md)).
 *
 * Names are the wiki's own; the lookup beside this file (`levels.ts`) resolves them against whatever
 * a caller has in hand. Nothing should import this file directly.
 *
 * 99 zones.
 */

/** A zone name → the levels its page states for the monsters there, as the wiki writes them. */
export const ZONE_LEVELS: Readonly<Record<string, string>> = {
  "Befallen": "7-25+",
  "Blackburrow": "4-15+",
  "Burning Wood": "40-55",
  "Butcherblock Mountains": "1-15, 35",
  "Cazic Thule (Zone)": "19-45",
  "Chardok (Post-Revamp)": "50+",
  "Chardok (Pre-Revamp)": "50+",
  "City of Mist": "35-55",
  "Cobalt Scar": "35-60+",
  "Crushbone": "5-20",
  "Crystal Caverns": "25-45",
  "Dagnor's Cauldron": "10-25",
  "Dalnir": "25-35+",
  "Dragon Necropolis": "45-60+",
  "Dreadlands": "35-50+",
  "East Commonlands": "1-20, 35",
  "Eastern Plains of Karana": "10-30+",
  "Eastern Wastes": "30-45",
  "Emerald Jungle": "35-45",
  "Erud's Crossing": "5-15",
  "Everfrost Peaks": "1-20+",
  "Field of Bone": "1-50+",
  "Firiona Vie": "25-35",
  "Frontier Mountains": "25-45",
  "Gorge of King Xorbb": "8-25",
  "Great Divide": "30-45",
  "Greater Faydark": "1-12",
  "High Keep": "20-40",
  "Highpass Hold": "9-22",
  "Howling Stones": "50+",
  "Iceclad Ocean": "30-40",
  "Icewell Keep": "45-60",
  "Innothule Swamp": "1-10, 25-30",
  "Kael Drakkel": "30-60+",
  "Kaesora": "30-40",
  "Karnor's Castle": "40-55+",
  "Kedge Keep": "32-50",
  "Kerra Island": "15-25",
  "Kithicor Forest": "1-13+, 35-50",
  "Kurn's Tower": "10-25",
  "Lake of Ill Omen": "1-30+",
  "Lake Rathetear": "15-35",
  "Lavastorm Mountains": "10-19, 25-30",
  "Lesser Faydark": "10-30, 40-50",
  "Lower Guk": "30-50+",
  "Mines of Nurga": "30-40",
  "Mistmoore Castle": "20-45",
  "Misty Thicket": "1-12",
  "Nagafen's Lair": "40-55",
  "Najena": "8-35",
  "Nektulos Forest": "1-20, 25-30",
  "Northern Plains of Karana": "10-30+",
  "Oasis of Marr": "7-30+",
  "Ocean of Tears": "9-30+",
  "Old Sebilis": "48-60",
  "Permafrost": "15-50+",
  "Plane of Fear": "48+",
  "Plane of Growth": "55+",
  "Plane of Hate": "48+",
  "Plane of Mischief": "50+",
  "Plane of Sky": "50+",
  "Qeynos": "1-9",
  "Qeynos Aqueducts": "1-15, 33-38",
  "Qeynos Hills": "2-10",
  "Rathe Mountains": "13-45",
  "Runnyeye": "7-30+",
  "Siren's Grotto": "50-60+",
  "Skyfire Mountains": "40-60+",
  "Skyshrine": "35-60",
  "Sleeper's Tomb": "55+",
  "Solusek's Eye": "20-40",
  "Southern Desert of Ro": "5-20+",
  "Southern Karana": "15-35",
  "Splitpaw Lair": "20-40",
  "Steamfont Mountains": "1-18, 30-35",
  "Stonebrunt Mountains": "14-46",
  "Swamp of No Hope": "1-25+",
  "Temple of Droga": "29-34 Droga Main, 33-38 Inner Sanctum",
  "Temple of Veeshan": "60+",
  "The Estate of Unrest": "10-35",
  "The Feerrott": "1-30, 34-40",
  "The Hole": "39-56",
  "The Northern Desert of Ro": "5-30+",
  "The Overthere": "20-40+ (50+ inside pit)",
  "The Wakening Land": "33-60+",
  "The Warrens": "4-25",
  "Thurgadin": "30-35 (in caves), 30-45 (dwarves)",
  "Timorous Deep": "20-55",
  "Tower of Frozen Shadow": "26-51",
  "Toxxulia Forest": "1-10",
  "Trakanon's Teeth": "30-55",
  "Tutorial Zone": "1",
  "Upper Guk": "4-25+",
  "Veeshan's Peak": "60+",
  "Velketor's Labyrinth": "45-60+",
  "Warsliks Woods": "1-30+",
  "West Commonlands": "6-30",
  "Western Karana": "4-20+",
  "Western Wastes": "45-60+",
};
