/**
 * Buff-line stacking data — GENERATED, do not edit by hand.
 *
 * Regenerate with `node scripts/fetch-buff-lines.mjs`, which fetches and parses eqlwiki's
 * "Buff Lines" (scraped 2026-09-21T17:44:54.168Z). Shipped rather than fetched at runtime —
 * see this script's own header and
 * [ADR 0264](../../specs/decisions/0264-buff-line-data-is-generated-static-data.md).
 *
 * Every entry is one buff line: a group of spells/items that can't be up on the same target at
 * once, because the game only ever keeps the strongest. A spell that appears under more than one
 * line is a combination buff that conflicts with everything under either one — that's just what
 * appearing twice already means, nothing more is encoded for it.
 *
 * `members` keeps only what the guide's bullet stated in a structurally regular way: the spell's
 * name, its bonus, and whatever trailed it as free-text `detail` (class/level, Group/Self-only, an
 * item's source) — see `scripts/lib/buff-lines-parse.mjs`'s header for why that isn't parsed any
 * further.
 *
 * The lookup over this is hand-written beside it in `buff-lines.ts`. Nothing should import this
 * file directly.
 *
 * 112 buff lines, 502 members.
 */

export interface BuffLineMember {
  spell: string;
  /** Signed — the guide states every real row this way (see its own "To Do" list on the ones it's
   *  still missing). */
  bonus: number;
  /** "%" for the handful of Haste rows the guide states as a percentage rather than a flat amount
   *  — absent otherwise, which reads as "flat". */
  unit?: string;
  /** Whatever else the guide wrote around the spell link, verbatim: a bard song's bonus with a
   *  maximum instrument, a resource cost, class/level, Group/Self-only, an item's source, a
   *  footnote — kept as free text rather than broken down further. */
  detail?: string;
}

/** One group of spells/items that can't be up on the same target at once. */
export interface BuffLine {
  /** Stable, derived from `stat`+`label` — not the wiki's own key, since the guide has none. */
  id: string;
  category: string;
  stat: string;
  /** The line's own name, shorter than `id` and fit to show beside a spell ("Primary", "Potion"). */
  label: string;
  /** Strongest first, as the guide lists them. */
  members: BuffLineMember[];
}

export const BUFF_LINES_SOURCE = { title: "Buff Lines", scrapedAt: "2026-09-21T17:44:54.169Z" };

export const BUFF_LINES: BuffLine[] = [
  {
    id: "agility--primary",
    category: "Attribute Enhancing",
    stat: "Agility",
    label: "Primary",
    members: [
        { spell: "Deliriously Nimble", bonus: 52, detail: "(Shaman 53)" },
        { spell: "Talisman of the Cat", bonus: 45, detail: "(Group) (Shaman 57)" },
        { spell: "Agility", bonus: 45, detail: "(Shaman 44)" },
        { spell: "Nimble", bonus: 36, detail: "(Shaman 34)" },
        { spell: "Spirit of Cat", bonus: 27, detail: "(Shaman 19)" },
        { spell: "Feet like Cat", bonus: 18, detail: "(Ranger 15, Shaman 5)" },
    ],
  },
  {
    id: "agility--speed-augmentation",
    category: "Attribute Enhancing",
    stat: "Agility",
    label: "Speed Augmentation",
    members: [
        { spell: "Speed of the Shissar", bonus: 40, detail: "(Click: Staff of the Serpent)" },
        { spell: "Visions of Grandeur", bonus: 40, detail: "(Enchanter 60)" },
        { spell: "Augment", bonus: 35, detail: "(Enchanter 56)" },
        { spell: "Augmentation", bonus: 30, detail: "(Enchanter 29)" },
    ],
  },
  {
    id: "agility--march",
    category: "Attribute Enhancing",
    stat: "Agility",
    label: "March",
    members: [
        { spell: "Nillipus' March of the Wee", bonus: 18, detail: "(+50) (Bard 52)" },
    ],
  },
  {
    id: "agility--song-of-the-deep-seas",
    category: "Attribute Enhancing",
    stat: "Agility",
    label: "Song of the Deep Seas",
    members: [
        { spell: "Song of the Deep Seas", bonus: 30, detail: "(Proc: Nature's Melody, Siren Song, Dagger of the Sea)" },
    ],
  },
  {
    id: "agility--avatar",
    category: "Attribute Enhancing",
    stat: "Agility",
    label: "Avatar",
    members: [
        { spell: "Avatar", bonus: 100, detail: "(Lasts 6 min, Shaman 60, Proc: Primal Velium Weapons)" },
        { spell: "Primal Essence", bonus: 20, detail: "(Click: Hammer of the Dragonborn)" },
    ],
  },
  {
    id: "agility--potion",
    category: "Attribute Enhancing",
    stat: "Agility",
    label: "Potion",
    members: [
        { spell: "Graveyard Dust", bonus: 26, detail: "(lasts 1.8m) (Consumable: Potion of Graveyard Dust)" },
        { spell: "Aura of Cold", bonus: 25, detail: "(Consumable: Greater Potion of Cold)" },
        { spell: "Accuracy", bonus: 15, detail: "(Consumable: Greater Potion of Accuracy)" },
        { spell: "Adroitness", bonus: 15, detail: "(Consumable: Greater Potion of Adroitness)" },
        { spell: "Aura of Cold", bonus: 15, detail: "(Consumable: Potion of Cold)" },
        { spell: "Vigor", bonus: 15, detail: "(Consumable: Greater Potion of Vigor)" },
        { spell: "Accuracy", bonus: 10, detail: "(Consumable: Potion of Accuracy)" },
        { spell: "Adroitness", bonus: 10, detail: "(Consumable: Potion of Adroitness)" },
        { spell: "Vigor", bonus: 10, detail: "(Consumable: Potion of Vigor)" },
        { spell: "Accuracy", bonus: 5, detail: "(Consumable: Potion of Lesser Accuracy)" },
        { spell: "Adroitness", bonus: 5, detail: "(Consumable: Potion of Lesser Adroitness)" },
        { spell: "Aura of Cold", bonus: 5, detail: "(Consumable: Minor Potion of Cold)" },
        { spell: "Vigor", bonus: 5, detail: "(Consumable: Potion of Lesser Vigor)" },
    ],
  },
  {
    id: "charisma--primary",
    category: "Attribute Enhancing",
    stat: "Charisma",
    label: "Primary",
    members: [
        { spell: "Unfailing Reverence", bonus: 55, detail: "(Shaman 59)" },
        { spell: "Overwhelming Splendor", bonus: 50, detail: "(Enchanter 56)" },
        { spell: "Talisman of the Serpent", bonus: 40, detail: "(Shaman 58)" },
        { spell: "Charisma", bonus: 40, detail: "(Shaman 49)" },
        { spell: "Adorning Grace", bonus: 40, detail: "(Enchanter 49)" },
        { spell: "Glamour", bonus: 32, detail: "(Shaman 39)" },
        { spell: "Radiant Visage", bonus: 30, detail: "(Enchanter 34)" },
        { spell: "Alluring Aura", bonus: 23, detail: "(Shaman 29)" },
        { spell: "Sympathetic Aura", bonus: 18, detail: "(Enchanter 20)" },
        { spell: "Spirit of Snake", bonus: 15, detail: "(Shaman 14)" },
    ],
  },
  {
    id: "charisma--bard-song",
    category: "Attribute Enhancing",
    stat: "Charisma",
    label: "Bard Song",
    members: [
        { spell: "Solon's Charismatic Concord", bonus: 45, detail: "(+126) (Bard 59)" },
    ],
  },
  {
    id: "charisma--potion",
    category: "Attribute Enhancing",
    stat: "Charisma",
    label: "Potion",
    members: [
        { spell: "Aura of Antibody", bonus: 25, detail: "(Consumable: Greater Potion of Antibody)" },
        { spell: "Aura of Antibody", bonus: 15, detail: "(Consumable: Potion of Antibody)" },
        { spell: "Aura of Antibody", bonus: 5, detail: "(Consumable: Minor Potion of Antibody)" },
    ],
  },
  {
    id: "dexterity--primary",
    category: "Attribute Enhancing",
    stat: "Dexterity",
    label: "Primary",
    members: [
        { spell: "Mortal Deftness", bonus: 60, detail: "(Shaman 58) *" },
        { spell: "Talisman of the Raptor", bonus: 60, detail: "(Group) (Shaman 59)" },
        { spell: "Dexterity", bonus: 50, detail: "(Shaman 49)" },
        { spell: "Deftness", bonus: 40, detail: "(Shaman 39)" },
        { spell: "Rising Dexterity", bonus: 30, detail: "(Shaman 29)" },
        { spell: "Spirit of Monkey", bonus: 20, detail: "(Shaman 24)" },
        { spell: "Dexterous Aura", bonus: 10, detail: "(Shaman 1)" },
    ],
  },
  {
    id: "dexterity--combination",
    category: "Attribute Enhancing",
    stat: "Dexterity",
    label: "Combination",
    members: [
        { spell: "Focus of Spirit", bonus: 60, detail: "(Shaman 60) *" },
    ],
  },
  {
    id: "dexterity--power",
    category: "Attribute Enhancing",
    stat: "Dexterity",
    label: "Power",
    members: [
        { spell: "Chant of Battle", bonus: 20, detail: "(+56) (Bard 1)" },
        { spell: "Visions of Grandeur", bonus: 25, detail: "(Enchanter 60)" },
        { spell: "Power", bonus: 15, detail: "(Consumable: Greater Potion of Power)" },
        { spell: "Power", bonus: 10, detail: "(Consumable: Potion of Power)" },
        { spell: "Power", bonus: 5, detail: "(Consumable: Potion of Lesser Power)" },
    ],
  },
  {
    id: "dexterity--illusion",
    category: "Attribute Enhancing",
    stat: "Dexterity",
    label: "Illusion",
    members: [
        { spell: "Boon of the Garou", bonus: 100, detail: "(Enchanter 44)" },
    ],
  },
  {
    id: "dexterity--avatar",
    category: "Attribute Enhancing",
    stat: "Dexterity",
    label: "Avatar",
    members: [
        { spell: "Avatar", bonus: 100, detail: "(Lasts 6 min, Shaman 60, Proc: Primal Velium Weapons)" },
        { spell: "Primal Essence", bonus: 20, detail: "(Click: Hammer of the Dragonborn)" },
    ],
  },
  {
    id: "dexterity--potion",
    category: "Attribute Enhancing",
    stat: "Dexterity",
    label: "Potion",
    members: [
        { spell: "Accuracy", bonus: 25, detail: "(Consumable: Greater Potion of Accuracy)" },
        { spell: "Cohesion", bonus: 25, detail: "(Consumable: Greater Potion of Cohesion)" },
        { spell: "Null Aura", bonus: 25, detail: "(Consumable: Greater Null Potion)" },
        { spell: "Null Aura", bonus: 15, detail: "(Consumable: Null Potion)" },
        { spell: "Accuracy", bonus: 10, detail: "(Consumable: Potion of Accuracy)" },
        { spell: "Cohesion", bonus: 10, detail: "(Consumable: Potion of Cohesion)" },
        { spell: "Accuracy", bonus: 5, detail: "(Consumable: Potion of Lesser Accuracy)" },
        { spell: "Cohesion", bonus: 5, detail: "(Consumable: Potion of Lesser Cohesion)" },
        { spell: "Null Aura", bonus: 5, detail: "(Consumable: Minor Null Potion)" },
    ],
  },
  {
    id: "dexterity--short-duration",
    category: "Attribute Enhancing",
    stat: "Dexterity",
    label: "Short Duration",
    members: [
        { spell: "Fleeting Fury", bonus: 20, detail: "(Shaman 5, Proc: Iksar Berserker Club)" },
    ],
  },
  {
    id: "intelligence--primary",
    category: "Attribute Enhancing",
    stat: "Intelligence",
    label: "Primary",
    members: [
        { spell: "Enlightenment", bonus: 22, detail: "(Enchanter 57)" },
        { spell: "Brilliance", bonus: 14, detail: "(Enchanter 44)" },
        { spell: "Insight", bonus: 9, detail: "(Enchanter 39)" },
    ],
  },
  {
    id: "intelligence--elegy",
    category: "Attribute Enhancing",
    stat: "Intelligence",
    label: "Elegy",
    members: [
        { spell: "Cassindra's Elegy", bonus: 16, detail: "(+44) (Bard 44)" },
    ],
  },
  {
    id: "stamina--primary",
    category: "Attribute Enhancing",
    stat: "Stamina",
    label: "Primary",
    members: [
        { spell: "Riotous Health", bonus: 50, detail: "(Shaman 54)" },
        { spell: "Talisman of the Brute", bonus: 40, detail: "(Group: Shaman 57)" },
        { spell: "Stamina", bonus: 40, detail: "(Shaman 44)" },
        { spell: "Health", bonus: 31, detail: "(Shaman 34)" },
        { spell: "Spirit of Ox", bonus: 23, detail: "(Shaman 24)" },
        { spell: "Spirit of Bear", bonus: 15, detail: "(Shaman 9)" },
    ],
  },
  {
    id: "stamina--potion-stability",
    category: "Attribute Enhancing",
    stat: "Stamina",
    label: "Potion: Stability",
    members: [
        { spell: "Aura of Heat", bonus: 25, detail: "(Consumable: Greater Potion of Heat)" },
        { spell: "Aura of Heat", bonus: 15, detail: "(Consumable: Potion of Heat)" },
        { spell: "Cohesion", bonus: 15, detail: "(Consumable: Greater Potion of Cohesion)" },
        { spell: "Stability", bonus: 15, detail: "(Consumable: Greater Potion of Stability)" },
        { spell: "Cohesion", bonus: 10, detail: "(Consumable: Potion of Cohesion)" },
        { spell: "Stability", bonus: 10, detail: "(Consumable: Potion of Stability)" },
        { spell: "Aura of Heat", bonus: 5, detail: "(Consumable: Minor Potion of Heat)" },
        { spell: "Cohesion", bonus: 5, detail: "(Consumable: Potion of Lesser Cohesion)" },
        { spell: "Stability", bonus: 5, detail: "(Consumable: Potion of Lesser Stability)" },
    ],
  },
  {
    id: "stamina--potion-adroitness",
    category: "Attribute Enhancing",
    stat: "Stamina",
    label: "Potion: Adroitness",
    members: [
        { spell: "Adroitness", bonus: 25, detail: "(Consumable: Greater Potion of Adroitness)" },
        { spell: "Adroitness", bonus: 10, detail: "(Consumable: Potion of Adroitness)" },
        { spell: "Adroitness", bonus: 5, detail: "(Consumable: Potion of Lesser Adroitness)" },
    ],
  },
  {
    id: "strength--primary",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Primary",
    members: [
        { spell: "Maniacal Strength", bonus: 68, detail: "(Shaman 57) *" },
        { spell: "Strength", bonus: 67, detail: "(Shaman 49)" },
        { spell: "Girdle of Karana", bonus: 42, detail: "(Druid 55)" },
        { spell: "Rampage", bonus: 42, detail: "(Enchanter 39, Proc: Axe of the Slayers, Thornstinger, Vehement Sword of Reivaj)" },
        { spell: "Talisman of the Rhino", bonus: 42, detail: "(Group) (Shaman 58)" },
        { spell: "Berserker Spirit", bonus: 40, detail: "(Enchanter 49)" },
        { spell: "Storm Strength", bonus: 35, detail: "(Druid 44, Ranger 53)" },
        { spell: "Furious Strength", bonus: 34, detail: "(Shaman 39)" },
        { spell: "Tumultuous Strength", bonus: 34, detail: "(Group) (Shaman 39)" },
        { spell: "Raging Strength", bonus: 26, detail: "(Shaman 29)" },
        { spell: "Strength of Stone", bonus: 25, detail: "(Druid 34)" },
        { spell: "Spirit Strength", bonus: 18, detail: "(Shaman 19)" },
        { spell: "Strength of Earth", bonus: 15, detail: "(Druid 9, Ranger 22)" },
        { spell: "Strengthen", bonus: 10, detail: "(Enchanter 1, Shaman 1)" },
    ],
  },
  {
    id: "strength--power",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Power",
    members: [
        { spell: "Focus of Spirit", bonus: 67, detail: "(Shaman 60)" },
        { spell: "Aura of Purity", bonus: 25, detail: "(Consumable: Greater Potion of Purity)" },
        { spell: "Power", bonus: 25, detail: "(Consumable: Greater Potion of Power)" },
        { spell: "Stability", bonus: 25, detail: "(Consumable: Greater Potion of Stability)" },
        { spell: "Aura of Purity", bonus: 15, detail: "(Consumable: Potion of Purity)" },
        { spell: "Power", bonus: 10, detail: "(Consumable: Potion of Power)" },
        { spell: "Stability", bonus: 10, detail: "(Consumable: Potion of Stability)" },
        { spell: "Vigor", bonus: 10, detail: "(Consumable: Potion of Vigor)" },
        { spell: "Aura of Purity", bonus: 5, detail: "(Consumable: Minor Potion of Purity)" },
        { spell: "Power", bonus: 5, detail: "(Consumable: Potion of Lesser Power)" },
        { spell: "Stability", bonus: 5, detail: "(Consumable: Potion of Lesser Stability)" },
        { spell: "Vigor", bonus: 5, detail: "(Consumable: Potion of Lesser Vigor)" },
    ],
  },
  {
    id: "strength--anthem",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Anthem",
    members: [
        { spell: "Anthem De Arms", bonus: 35, detail: "(+98) (Group) (Bard 10)" },
        { spell: "Jonthan's Whistling Warsong", bonus: 32, detail: "(+89) (Self-only: Bard 7)" },
        { spell: "Chant of Battle", bonus: 20, detail: "(+56) (Bard 1)" },
        { spell: "Niv's Melody of Preservation", bonus: 10, detail: "(+28) (Bard 47)" },
        { spell: "McVaxius' Rousing Rondo", bonus: 21, detail: "(+58) (Bard 57)" },
    ],
  },
  {
    id: "strength--dance",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Dance",
    members: [
        { spell: "Dance of the Blade", bonus: 30, detail: "(Click: Singing Short Sword)" },
    ],
  },
  {
    id: "strength--song",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Song",
    members: [
        { spell: "Song of the Deep Seas", bonus: 30, detail: "(Click: Nature's Melody, Siren Song, Dagger of the Sea)" },
    ],
  },
  {
    id: "strength--illusion",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Illusion",
    members: [
        { spell: "Illusion: Werewolf", bonus: 30, detail: "(Self-only: Enchanter 44, Click: Lute of the Howler)" },
        { spell: "Illusion: Earth Elemental", bonus: 10, detail: "(Self-only: Enchanter 24, Consumable: Ball of Golem Clay)" },
    ],
  },
  {
    id: "strength--avatar",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Avatar",
    members: [
        { spell: "Avatar", bonus: 100, detail: "(Lasts 6 min, Shaman 60, Proc: Primal Velium Weapons)" },
        { spell: "Primal Essence", bonus: 20, detail: "(Click: Hammer of the Dragonborn)" },
    ],
  },
  {
    id: "strength--potion",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Potion",
    members: [
        { spell: "Can o' Whoop Ass", bonus: 75, detail: "(Consumable (GM Event, Lasts 1 min): Can o` Whoop Ass)" },
        { spell: "Graveyard Dust", bonus: 26, detail: "(lasts 1.8m) (Consumable: Potion of Graveyard Dust)Wort]])" },
        { spell: "Dulsehound", bonus: 18, detail: "(lasts 3m) (Consumable: Potion of Dulsehound)" },
        { spell: "Screaming Mace (Spell)", bonus: 10, detail: "(Proc:: Screaming Mace)" },
        { spell: "Calimony", bonus: 17, detail: "(lasts 6m) (Consumable: Potion of Stinging Wort)" },
    ],
  },
  {
    id: "strength--short-duration",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Short Duration",
    members: [
        { spell: "Burst of Strength", bonus: 20, detail: "(Self-only: Shaman 14)" },
        { spell: "Fleeting Fury", bonus: 15, detail: "(Shaman 5, Proc: Iksar Berserker Club)" },
    ],
  },
  {
    id: "strength--short-duration-yaulp",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Short Duration: Yaulp",
    members: [
        { spell: "Yaulp IV", bonus: 40, detail: "( Cleric 53l, Paladin 60, Proc: Claw of Phara Dar)" },
        { spell: "Yaulp III", bonus: 30, detail: "(Cleric 44, Paladin 56, Proc: Warhammer of Divine Grace)" },
        { spell: "Yaulp II", bonus: 20, detail: "(Cleric 19, Paladin 39, Click:: Donal's Helm of Mourning, Mask of War, Proc: Brell's Keg Popper, Frost Giant Femur, Shrieking Ahlspiess)" },
        { spell: "Yaulp", bonus: 10, detail: "(Cleric 1, Paladin 9, Click:: Initiate Symbol of Rallos Zek, Proc: Hammer of Rage)" },
    ],
  },
  {
    id: "strength--short-duration-bedlam",
    category: "Attribute Enhancing",
    stat: "Strength",
    label: "Short Duration: Bedlam",
    members: [
        { spell: "Bedlam", bonus: 50, detail: "(Enchanter 58)" },
        { spell: "Berserker Strength", bonus: 25, detail: "(3 min) (Enchanter 20)" },
    ],
  },
  {
    id: "wisdom--enchanter",
    category: "Attribute Enhancing",
    stat: "Wisdom",
    label: "Enchanter",
    members: [
        { spell: "Enlightenment", bonus: 22, detail: "(Enchanter 57)" },
        { spell: "Insight", bonus: 14, detail: "(Enchanter 39)" },
        { spell: "Brilliance", bonus: 7, detail: "(Enchanter 44)" },
    ],
  },
  {
    id: "wisdom--elegy",
    category: "Attribute Enhancing",
    stat: "Wisdom",
    label: "Elegy",
    members: [
        { spell: "Cassindra's Elegy", bonus: 16, detail: "(+44) (Bard 44)" },
    ],
  },
  {
    id: "wisdom--illusion-shaman-self-only",
    category: "Attribute Enhancing",
    stat: "Wisdom",
    label: "Illusion, Shaman Self-Only",
    members: [
        { spell: "Form of the Great Bear", bonus: 10, detail: "(Self-only: Shaman 55)" },
    ],
  },
  {
    id: "ac--slot-1-4",
    category: "Other Buffs",
    stat: "AC",
    label: "Slot 1 & 4",
    members: [
        { spell: "Aegolism", bonus: 54, detail: "(Cleric 60)" },
    ],
  },
  {
    id: "ac--slot-1",
    category: "Other Buffs",
    stat: "AC",
    label: "Slot 1",
    members: [
        { spell: "Protection of the Glades", bonus: 24, detail: "(Druid 60)" },
        { spell: "Heroism", bonus: 19, detail: "(Cleric 52)" },
        { spell: "Natureskin", bonus: 19, detail: "(Druid 57)" },
        { spell: "Fortitude", bonus: 18, detail: "(Cleric 55, Consumable: Invigorating Spores)" },
        { spell: "Resolution", bonus: 16, detail: "(Cleric 44, Paladin 60)" },
        { spell: "Skin Like Nature", bonus: 16, detail: "(Druid 49, Ranger 59, Click: Robe of the Spring)" },
        { spell: "Skin Like Diamond", bonus: 13, detail: "(Druid 39, Ranger 54, Click: Elder Spiritist's Greaves)" },
        { spell: "Valor", bonus: 13, detail: "(Cleric 34, Paladin 49, Click: Donal's Vambraces of Mourning)" },
        { spell: "Skin Like Steel", bonus: 10, detail: "(Druid 24, Ranger 39)" },
        { spell: "Bravery", bonus: 10, detail: "(Cleric 24)" },
        { spell: "Daring", bonus: 9, detail: "(Cleric 19, Paladin 39, Click: Deepwater Helm)" },
        { spell: "Skin Like Rock", bonus: 7, detail: "(Druid 14, Ranger 22, Click: Mountain Death Belt, Consumable: Shard of Golem Stone)" },
        { spell: "Center", bonus: 6, detail: "(Cleric 9, Paladin 22)" },
        { spell: "Courage", bonus: 4, detail: "(Cleric 1, Paladin 9, Click: Golden Locket (Locket of Courage))" },
        { spell: "Skin Like Wood", bonus: 4, detail: "(Druid 1, Ranger 9)" },
        { spell: "Inner Fire", bonus: 3, detail: "(Shaman 1)" },
    ],
  },
  {
    id: "ac--slot-2",
    category: "Other Buffs",
    stat: "AC",
    label: "Slot 2",
    members: [
        { spell: "Shield of the Magi", bonus: 42, detail: "(Self-only: Enchanter 54, Magician 54, Necromancer 54, Wizard 54)" },
        { spell: "Bladecoat", bonus: 37, detail: "(Self-only: Druid 56)" },
        { spell: "Arch Shielding", bonus: 35, detail: "(Self-only: Enchanter 44, Magician 44, Necromancer 44, Wizard 44, Click: Tri-Plated Golden Hackle Hammer)" },
        { spell: "Thorncoat", bonus: 31, detail: "(Self-only: Druid 49, Ranger 60)" },
        { spell: "Greater Shielding", bonus: 29, detail: "(Self-only: Enchanter 34, Magician 34, Necromancer 34, Wizard 34)" },
        { spell: "Spikecoat", bonus: 25, detail: "(Self-only: Druid 39, Ranger 49, Click: Girdle of Living Thorns)" },
        { spell: "Major Shielding", bonus: 23, detail: "(Self-only: Enchanter 24, Magician 24, Necromancer 24, Wizard 24, Click: Blood Ember Breastplate, Proc: Stave of Shielding)" },
        { spell: "Bramblecoat", bonus: 18, detail: "(Self-only: Druid 29, Ranger 39, Click: Jaundiced Bone Breastplate)" },
        { spell: "Shielding", bonus: 18, detail: "(Self-only: Enchanter 16, Magician 16, Necromancer 16, Wizard 16" },
        { spell: "Armor of Protection", bonus: 15, detail: "(Self-only: Cleric 34)" },
        { spell: "Yaulp IV", bonus: 15, detail: "(Cleric 53, Paladin 60, Proc: Claw of Phara Dar)" },
        { spell: "Barbcoat", bonus: 12, detail: "(Self-only: Druid 19, Ranger 30)" },
        { spell: "Yaulp III", bonus: 12, detail: "(Cleric 44, Paladin 56, Proc: Warhammer of Divine Grace)" },
        { spell: "Lesser Shielding", bonus: 9, detail: "(Self-only: Enchanter 8, Magician 8, Necromancer 8, Wizard 8, Click: Cobalt Vambraces)" },
        { spell: "Yaulp II", bonus: 8, detail: "(Cleric 19, Paladin 39, Click: Donal's Helm of Mourning, Mask of War, Proc: Brell's Keg Popper, Frost Giant Femur, Shrieking Ahlspiess)" },
        { spell: "Thistlecoat", bonus: 6, detail: "(Self-only: Druid 9, Ranger 15)" },
        { spell: "Yaulp", bonus: 6, detail: "(Cleric 1, Paladin 9, Click: Initiate Symbol of Rallos Zek, Proc: Hammer of Rage)" },
        { spell: "Minor Shielding", bonus: 4, detail: "(Enchanter 1, Magician 1, Necromancer 1, Wizard 1)" },
    ],
  },
  {
    id: "ac--slot-3",
    category: "Other Buffs",
    stat: "AC",
    label: "Slot 3",
    members: [
        { spell: "Call of Earth", bonus: 25, detail: "(Ranger 50, Click: Breastplate of the Untamed, Forest Stalker's Breastplate, Golden Leaf Breastplate, Runed Scout's Breastplate)" },
        { spell: "Augment", bonus: 18, detail: "(Enchanter 56)" },
        { spell: "Speed of the Shissar", bonus: 12, detail: "(Click: Staff of the Serpent)" },
        { spell: "Frenzy", bonus: 10, detail: "(Self-only Shaman 19)" },
        { spell: "Augmentation", bonus: 9, detail: "(Enchanter 29)" },
        { spell: "Fleeting Fury", bonus: 6, detail: "(Shaman 5, Proc: Iksar Berserker Club)" },
        { spell: "Screaming Mace (Spell)", bonus: 6, detail: "(Proc: Screaming Mace)" },
    ],
  },
  {
    id: "ac--slot-4",
    category: "Other Buffs",
    stat: "AC",
    label: "Slot 4",
    members: [
        { spell: "Bulwark of Faith", bonus: 37, detail: "(Cleric 57)" },
        { spell: "Aegis", bonus: 34, detail: "(Cleric 57)" },
        { spell: "Shield of Words", bonus: 31, detail: "(Cleric 49, Paladin 60)" },
        { spell: "Umbra", bonus: 29, detail: "(Enchanter 57)" },
        { spell: "Shroud of the Spirits", bonus: 28, detail: "(Shaman 54)" },
        { spell: "Armor of Faith", bonus: 25, detail: "(Cleric 39, Paladin 49, Click: Donal's Gauntlets of Mourning)" },
        { spell: "Guardian", bonus: 24, detail: "(Shaman 44)" },
        { spell: "Phantom Armor", bonus: 22, detail: "(Magician 52)" },
        { spell: "Guard", bonus: 19, detail: "(Cleric 29, Paladin 39, Click: Bone Amulet of Blade Turning, Proc: Guardians Mace, Star of the Guardian, Warding Star)" },
        { spell: "Shadow", bonus: 19, detail: "(Enchanter 49) (Proc: Crescent Blades of Luclin)" },
        { spell: "Phantom Plate", bonus: 18, detail: "(Magician 44, Click: Shissar Guardian Staff)" },
        { spell: "Shifting Shield", bonus: 18, detail: "(Shaman 34, Consumable: Potion of Spirit Shield)" },
        { spell: "Shade", bonus: 16, detail: "(Enchanter 39)" },
        { spell: "Obscure", bonus: 13, detail: "(Enchanter 29)" },
        { spell: "Phantom Chain", bonus: 13, detail: "(Magician 29)" },
        { spell: "Protect", bonus: 13, detail: "(Shaman 24)" },
        { spell: "Spirit Armor", bonus: 13, detail: "(Cleric 19, Necromancer 16, Paladin 30, Proc: Shieldstorm)" },
        { spell: "Cloud", bonus: 10, detail: "(Enchanter 20, Click: Runed Sea Shell (Cloud))" },
        { spell: "Turtle Skin", bonus: 10, detail: "(Shaman 14, Click: Lodizal Shell Boots)" },
        { spell: "Phantom Leather", bonus: 9, detail: "(Magician 16)" },
        { spell: "Mist", bonus: 7, detail: "(Enchanter 12)" },
        { spell: "Holy Armor", bonus: 6, detail: "(Cleric 5, Paladin 15)" },
        { spell: "Scale Skin", bonus: 6, detail: "(Shaman 5, Consumable: Serpent's Drink)" },
        { spell: "Haze", bonus: 4, detail: "(Enchanter 4)" },
    ],
  },
  {
    id: "ac--slot-7",
    category: "Other Buffs",
    stat: "AC",
    label: "Slot 7",
    members: [
        { spell: "Shroud of Pain Recourse", bonus: 18, detail: "(Shadow Knight 50)" },
        { spell: "Shadow Vortex Recourse", bonus: 12, detail: "(Necromancer 20, Shadow Knight 39, Proc: Cazic Quill, Twisted Oaken Staff)" },
    ],
  },
  {
    id: "ac--slot-8",
    category: "Other Buffs",
    stat: "AC",
    label: "Slot 8",
    members: [
        { spell: "Celestial Tranquility", bonus: 12, detail: "(Click: Celestial Fists)" },
    ],
  },
  {
    id: "ac--slot-9",
    category: "Other Buffs",
    stat: "AC",
    label: "Slot 9",
    members: [
        { spell: "Song of the Deep Seas", bonus: 15, detail: "(Group Proc: Nature's Melody, Siren Song, Dagger of the Sea)" },
    ],
  },
  {
    id: "ac--layer-2-slot-1",
    category: "Other Buffs",
    stat: "AC",
    label: "Layer 2, Slot 1",
    members: [
        { spell: "Guardian Rhythms", bonus: 9, detail: "(+25) (Group: Bard 9)" },
        { spell: "Nillipus' March of the Wee", bonus: 9, detail: "(+25) (Group: Bard 52)" },
        { spell: "Chant of Battle", bonus: 6, detail: "(+16) (Group: Bard 1, Proc: Harmonic Spear)" },
    ],
  },
  {
    id: "ac--layer-2-slot-2",
    category: "Other Buffs",
    stat: "AC",
    label: "Layer 2, Slot 2",
    members: [
        { spell: "Niv's Harmonic", bonus: 24, detail: "(+67) (Group: Bard 58)" },
    ],
  },
  {
    id: "ac--layer-2-slot-3",
    category: "Other Buffs",
    stat: "AC",
    label: "Layer 2, Slot 3",
    members: [
        { spell: "Jonthan's Whistling Warsong", bonus: 10, detail: "(+28) (Self-only: Bard 7, Click: Robe of the Whistling Fists)" },
    ],
  },
  {
    id: "ac--layer-2-slot-4",
    category: "Other Buffs",
    stat: "AC",
    label: "Layer 2, Slot 4",
    members: [
        { spell: "Elemental Rhythms", bonus: 6, detail: "(+16) (Group: Bard 9)" },
        { spell: "Psalm of Warmth", bonus: 6, detail: "(+16) (Group: Bard 25)" },
        { spell: "Psalm of Vitality", bonus: 6, detail: "(+16) (Group: Bard 29)" },
        { spell: "Purifying Rhythms", bonus: 6, detail: "(+16) (Group: Bard 9)" },
    ],
  },
  {
    id: "attack-atk--slot-1",
    category: "Other Buffs",
    stat: "Attack (ATK)",
    label: "Slot 1",
    members: [
        { spell: "Celestial Tranquility", bonus: 40, detail: "(Click: Celestial Fists)" },
        { spell: "Strength of Nature", bonus: 25, detail: "(Ranger 51)" },
        { spell: "Yaulp IV", bonus: 16, detail: "(Self-only: Cleric 53, Paladin 60, Proc: Claw of Phara Dar)" },
        { spell: "Firefist", bonus: 10, detail: "(Self-only: Druid 9, Ranger 22, Click: Berserkers Ring, Golden Star Slippers, Grand Master's Slippers, Silver Moon Slippers, White Lotus Slippers)" },
        { spell: "Grim Aura", bonus: 10, detail: "(Self-only: Necromancer 4, Shadow Knight 22, Click: Hand of Shadow, Reaper's Ring, Shrunken Goblin Skull Earring, Sword of Pain)" },
    ],
  },
  {
    id: "attack-atk--slot-2",
    category: "Other Buffs",
    stat: "Attack (ATK)",
    label: "Slot 2",
    members: [
        { spell: "Illusion: Werewolf", bonus: 61, detail: "(Self-only: Enchanter 44, Click: Lute of the Howler)" },
        { spell: "Call of the Predator", bonus: 40, detail: "(Group: Ranger 60)" },
        { spell: "Illusion: Spirit Wolf", bonus: 15, detail: "(Self-only: Enchanter 39)" },
    ],
  },
  {
    id: "attack-atk--slot-3",
    category: "Other Buffs",
    stat: "Attack (ATK)",
    label: "Slot 3",
    members: [
        { spell: "Avatar", bonus: 100, detail: "(Shaman 60, Proc: Primal Velium Weapons)" },
        { spell: "Form of the Hunter", bonus: 62, detail: "(Self-only: Druid 60)" },
        { spell: "Form of the Great Wolf", bonus: 51, detail: "(Self-only: Druid 44)" },
        { spell: "Greater Wolf Form", bonus: 40, detail: "(Self-only: Druid 34, Ranger 56, Proc: Lupine Dagger)" },
        { spell: "Boon of the Garou", bonus: 30, detail: "(Enchanter 44)" },
        { spell: "Share Wolf Form", bonus: 30, detail: "(Group: Druid 39, Click: Elder Spiritist's Bracer)" },
        { spell: "Wolf Form", bonus: 30, detail: "(Self-only: Druid 24, Ranger 49)" },
        { spell: "Aura of Battle", bonus: 10, detail: "(Click: Fearsome Shield, Pauldrons of Ferocity)" },
    ],
  },
  {
    id: "attack-atk--slot-4",
    category: "Other Buffs",
    stat: "Attack (ATK)",
    label: "Slot 4",
    members: [
        { spell: "Visions of Grandeur", bonus: 20, detail: "(Enchanter 60)" },
    ],
  },
  {
    id: "attack-atk--slot-5",
    category: "Other Buffs",
    stat: "Attack (ATK)",
    label: "Slot 5",
    members: [
        { spell: "Frostreaver's Blessing", bonus: 10, detail: "(Click: Ring of Dain Frostreaver IV)" },
    ],
  },
  {
    id: "attack-atk--slot-7",
    category: "Other Buffs",
    stat: "Attack (ATK)",
    label: "Slot 7",
    members: [
        { spell: "Shroud of Hate Recourse", bonus: 20, detail: "(Self-only: Shadow Knight 39)" },
    ],
  },
  {
    id: "attack-atk--slot-12",
    category: "Other Buffs",
    stat: "Attack (ATK)",
    label: "Slot 12",
    members: [
        { spell: "Dance of the Blade", bonus: 30, detail: "(Group Proc: Singing Short Sword)" },
    ],
  },
  {
    id: "attack-atk--layer-2-slot-3-4",
    category: "Other Buffs",
    stat: "Attack (ATK)",
    label: "Layer 2, Slot 3 & 4",
    members: [
        { spell: "Jonthan's Provocation", bonus: 17, detail: "(+47) (Self-only: Bard 45)" },
        { spell: "Jonthan's Inspiration", bonus: 16, detail: "(+44) (Self-only: Bard 58)" },
        { spell: "McVaxius' Rousing Rondo", bonus: 14, detail: "(+39) (Group: Bard 57)" },
    ],
  },
  {
    id: "attack-atk--worn",
    category: "Other Buffs",
    stat: "Attack (ATK)",
    label: "Worn",
    members: [
        { spell: "Seething Fury", bonus: 40, detail: "(Worn: Ragebringer)" },
        { spell: "Rage of Tallon", bonus: 30, detail: "(Worn: Blade of Tactics)" },
        { spell: "Swift Spirit", bonus: 30, detail: "(Worn: Swiftwind)" },
        { spell: "Aura of Battle", bonus: 10, detail: "/item (Worn: Belt of Dwarf Slaying, Belt of the Great Turtle, Boots of Deep Thought, Boots of Silent Striding, Chestplate of Vindication, Silver Mask of the Slayer, Spirit Wracked Cord)" },
        { spell: "Firefist", bonus: 10, detail: "(Worn: Blazing Gauntlets of Fennin Ro)" },
    ],
  },
  {
    id: "damage-absorption--primary",
    category: "Other Buffs",
    stat: "Damage Absorption",
    label: "Primary",
    members: [
        { spell: "Barrier of Force", bonus: 800, detail: "(Click: Staff of the Four)" },
        { spell: "Rune V", bonus: 700, detail: "(Enchanter 52)" },
        { spell: "Manaskin", bonus: 600, detail: "(Self-only: Necromancer 52, Wizard 52)" },
        { spell: "Rune IV", bonus: 394, detail: "(Enchanter 44)" },
        { spell: "Diamondskin", bonus: 394, detail: "(Self-only: Necromancer 44, Shadow Knight 59, Wizard 44, Click:: Diamond Rod)" },
        { spell: "Rune III", bonus: 230, detail: "(Enchanter 34)" },
        { spell: "Steelskin", bonus: 230, detail: "(Self-only: Necromancer 34, Shadow Knight 56, Wizard 34)" },
        { spell: "Rune II", bonus: 118, detail: "(Enchanter 24)" },
        { spell: "Leatherskin", bonus: 118, detail: "(Self-only: Necromancer 24, Wizard 24)" },
        { spell: "Rampage", bonus: 90, detail: "(Enchanter 39, Proc: Axe of the Slayers, Thornstinger, Vehement Sword of Reivaj)" },
        { spell: "Rune I", bonus: 55, detail: "(Enchanter 16)" },
        { spell: "Shieldskin", bonus: 55, detail: "(Self-Only: Necromancer 16, Shadow Knight 34, Wizard 16)" },
    ],
  },
  {
    id: "damage-absorption--berserker",
    category: "Other Buffs",
    stat: "Damage Absorption",
    label: "Berserker",
    members: [
        { spell: "Bedlam", bonus: 350, detail: "(Enchanter 58)" },
        { spell: "Berserker Spirit", bonus: 200, detail: "(Enchanter 49)" },
        { spell: "Berserker Strength", bonus: 50, detail: "(Enchanter 20)" },
    ],
  },
  {
    id: "damage-absorption--shield-of-song",
    category: "Other Buffs",
    stat: "Damage Absorption",
    label: "Shield of Song",
    members: [
        { spell: "Shield of Song", bonus: 20, detail: "(+56) (Bard 49)" },
    ],
  },
  {
    id: "damage-absorption--march",
    category: "Other Buffs",
    stat: "Damage Absorption",
    label: "March",
    members: [
        { spell: "Nillipus' March of the Wee", bonus: 9, detail: "(+33) (Bard 52)" },
    ],
  },
  {
    id: "damage-absorption--gm-item",
    category: "Other Buffs",
    stat: "Damage Absorption",
    label: "GM Item",
    members: [
        { spell: "Can o' Whoop Ass", bonus: 4000, detail: "Damage Absorb (Consumable (GM Event, Lasts 1 min): Can o` Whoop Ass)" },
    ],
  },
  {
    id: "damage-absorption-magic--song-shield",
    category: "Other Buffs",
    stat: "Damage Absorption, Magic",
    label: "Song Shield",
    members: [
        { spell: "Shield of Song", bonus: 20, detail: "(+56) (Bard 49)" },
    ],
  },
  {
    id: "damage-absorption-magic--psalm",
    category: "Other Buffs",
    stat: "Damage Absorption, Magic",
    label: "Psalm",
    members: [
        { spell: "Psalm of Mystic Shielding", bonus: 15, detail: "(+42) (Bard 41)" },
    ],
  },
  {
    id: "damage-absorption-magic--melody",
    category: "Other Buffs",
    stat: "Damage Absorption, Magic",
    label: "Melody",
    members: [
        { spell: "Niv's Melody of Preservation", bonus: 10, detail: "(+28) (Bard 47)" },
    ],
  },
  {
    id: "damage-absorption-magic--manasink",
    category: "Other Buffs",
    stat: "Damage Absorption, Magic",
    label: "Manasink",
    members: [
        { spell: "Manasink", bonus: 250, detail: "(Self-only: Wizard 58)" },
    ],
  },
  {
    id: "damage-shield-stacking--slot-1",
    category: "Other Buffs",
    stat: "Damage Shield Stacking",
    label: "Slot 1",
    members: [
        { spell: "Aegis of Ro", bonus: 33, detail: "(Group: Magician 60)" },
        { spell: "Cadeau of Flame", bonus: 33, detail: "(Magician 56)" },
        { spell: "Shield of Blades", bonus: 32, detail: "(Druid 58)" },
        { spell: "Legacy of Thorn", bonus: 28, detail: "(Group: Druid 59)" },
        { spell: "Aegis of Bathezid", bonus: 25, detail: "(Click: Regal Band of Bathezid)" },
        { spell: "Boon of Immolation", bonus: 25, detail: "(Group: Magician 53)" },
        { spell: "Shield of Lava", bonus: 25, detail: "(Magician 49, Click: Arch Mage's Robe, Prestidigitator's Robe, Robe of Conjuration, Summoner's Robe, Consumable: Lava Diamond, Ro's Breath, Wand of Lava)" },
        { spell: "Shield of Thorns (Spell)", bonus: 24, detail: "(Druid 49, Click: Gloves of Earthcrafting)" },
        { spell: "Barrier of Combustion", bonus: 20, detail: "(Magician 39)" },
        { spell: "Shield of Spikes", bonus: 17, detail: "(Druid 39, Ranger 58)" },
        { spell: "Inferno Shield", bonus: 15, detail: "(Magician 29, Consumable: Lava Potion)" },
        { spell: "Shield of Brambles", bonus: 12, detail: "(Druid 29, Ranger 49, Proc: Arydryidriyorn and Yannikil)" },
        { spell: "Banshee Aura", bonus: 12, detail: "(Necromancer 16, Shadow Knight 54)" },
        { spell: "Feedback", bonus: 11, detail: "(Enchanter 29, Click: Earring of Blazing Energy)" },
        { spell: "Shield of Flame", bonus: 9, detail: "(Magician 20, Click: Blazing Vambraces, Singing Steel Bracer, Proc: Charred Black Staff)" },
        { spell: "Shield of Barbs", bonus: 9, detail: "(Druid 19)" },
        { spell: "Shield of Thistles", bonus: 6, detail: "(Druid 9, Ranger 30, Proc: Two Handed Practice Sword)" },
        { spell: "Shield of Fire", bonus: 5, detail: "(Magician 8)" },
        { spell: "O'Keils Radiation", bonus: 2, detail: "(Wizard 4, Click: Boots of the Invoker, Icicle Boots, Sage's Boots, Sorcerer's Boots)" },
    ],
  },
  {
    id: "damage-shield-stacking--slot-2",
    category: "Other Buffs",
    stat: "Damage Shield Stacking",
    label: "Slot 2",
    members: [
        { spell: "Kilva's Skin of Flame (Spell)", bonus: 31, detail: "(Consumable: Kilva's Skin of Flame)" },
        { spell: "Illusion: Fire Elemental", bonus: 16, detail: "(Self-only: Enchanter 34)" },
        { spell: "Scorching Skin", bonus: 16, detail: "(Consumable: Kilva's Blistering Flesh)" },
        { spell: "Frostreaver's Blessing", bonus: 10, detail: "(Click: Ring of Dain Frostreaver IV)" },
        { spell: "Shield of the Eighth", bonus: 8, detail: "(Click: Coldain Hero's Insignia Ring, Velium Coldain Insignia Ring)" },
        { spell: "O'Keils Flickering Flame", bonus: 5, detail: "(Wizard 34)" },
        { spell: "Call of Earth", bonus: 4, detail: "(Ranger 50)" },
    ],
  },
  {
    id: "damage-shield-stacking--slot-3",
    category: "Other Buffs",
    stat: "Damage Shield Stacking",
    label: "Slot 3",
    members: [
        { spell: "Bladecoat", bonus: 6, detail: "(Self-only: Druid 56)" },
        { spell: "Thorncoat", bonus: 5, detail: "(Self-only: Druid 49, Ranger 60)" },
        { spell: "Spikecoat", bonus: 4, detail: "(Self-only: Druid 39, Ranger 49, Click: Girdle of Living Thorns)" },
        { spell: "Bramblecoat", bonus: 3, detail: "(Self-only: Druid 29, Ranger 39, Click: Jaundiced Bone Breastplate)" },
        { spell: "Barbcoat", bonus: 2, detail: "(Self-only: Druid 19, Ranger 30)" },
        { spell: "Thistlecoat", bonus: 1, detail: "(Self-only: Druid 9, Ranger 15)" },
    ],
  },
  {
    id: "damage-shield-stacking--slot-4",
    category: "Other Buffs",
    stat: "Damage Shield Stacking",
    label: "Slot 4",
    members: [
        { spell: "Thorny Shield", bonus: 1, detail: "(Click: Cloak of Thorns)" },
    ],
  },
  {
    id: "damage-shield-stacking--layer-2-slot-1",
    category: "Other Buffs",
    stat: "Damage Shield Stacking",
    label: "Layer 2, Slot 1",
    members: [
        { spell: "Psalm of Cooling", bonus: 13, detail: "(+36) (Bard 33)" },
        { spell: "Psalm of Warmth", bonus: 13, detail: "(+36) (Bard 25)" },
    ],
  },
  {
    id: "damage-shield-stacking--layer-2-slot-4",
    category: "Other Buffs",
    stat: "Damage Shield Stacking",
    label: "Layer 2, Slot 4",
    members: [
        { spell: "McVaxius' Rousing Rondo", bonus: 8, detail: "(+22) (Bard 57)" },
    ],
  },
  {
    id: "haste--primary",
    category: "Other Buffs",
    stat: "Haste",
    label: "Primary",
    members: [
        { spell: "Can o' Whoop Ass", bonus: 200, unit: "%", detail: "(Consumable (GM Event, Lasts 1 min): Can o` Whoop Ass)" },
        { spell: "Wonderous Rapidity", bonus: 70, unit: "%", detail: "(Enchanter 58)" },
        { spell: "Speed of the Shissar", bonus: 66, unit: "%", detail: "(Click: Staff of the Serpent)" },
        { spell: "Graveyard Dust", bonus: 65, unit: "%", detail: "(lasts 1.8m) (Consumable: Potion of Graveyard Dust)" },
        { spell: "Aanya's Quickening", bonus: 64, unit: "%", detail: "(Enchanter 53)" },
        { spell: "Jonthan's Inspiration", bonus: 63, unit: "%", detail: "(Bard 58)" },
        { spell: "Swift Like The Wind", bonus: 60, unit: "%", detail: "(Enchanter 49)" },
        { spell: "Visions of Grandeur", bonus: 58, unit: "%", detail: "(Enchanter 60)" },
        { spell: "Dance of the Blade", bonus: 55, unit: "%", detail: "(Click: Singing Short Sword)" },
        { spell: "Celerity", bonus: 50, unit: "%", detail: "(Enchanter 39, Shaman 56)" },
        { spell: "Jonthan's Provocation", bonus: 50, unit: "%", detail: "(Bard 45)" },
        { spell: "Haste", bonus: 50, unit: "%", detail: "(Ranger 40, Self-Only Click: :Dark Cloak of the Sky)" },
        { spell: "Augment", bonus: 45, unit: "%", detail: "(Enchanter 56)" },
        { spell: "Vilia's Chorus of Celerity", bonus: 45, unit: "%", detail: "(Bard 54)" },
        { spell: "Flurry", bonus: 40, unit: "%", detail: "(Consumable: Adrenaline Tap)" },
        { spell: "Illusion: Werewolf", bonus: 40, unit: "%", detail: "(Self-only: Enchanter 44, Click: Lute of the Howler)" },
        { spell: "Quickness", bonus: 30, unit: "%", detail: "(Enchanter 16, Shaman 29)" },
        { spell: "Verses of Victory", bonus: 30, unit: "%", detail: "(Bard 50)" },
        { spell: "Augmentation", bonus: 28, unit: "%", detail: "(Enchanter 29)" },
        { spell: "Jonthan's Whistling Warsong", bonus: 25, unit: "%", detail: "(Bard) 7)" },
        { spell: "McVaxius' Berserker Crescendo", bonus: 23, unit: "%", detail: "(Group) (Bard) 42)" },
        { spell: "McVaxius' Rousing Rondo", bonus: 22, unit: "%", detail: "(Bard 57)" },
        { spell: "Captain Nalots Quickening", bonus: 20, unit: "%", detail: "(Eyepatch of Plunder)" },
        { spell: "Flurry", bonus: 20, unit: "%", detail: "(Consumable: Vial of Tamed Mercury)" },
        { spell: "Vilia's Verses of Celerity", bonus: 20, unit: "%", detail: "(Group) (Bard 36)" },
        { spell: "Anthem De Arms", bonus: 10, unit: "%", detail: "(Group) (Bard 10)" },
    ],
  },
  {
    id: "haste--ervaj-v2",
    category: "Other Buffs",
    stat: "Haste",
    label: "Ervaj/\"v2\"",
    members: [
        { spell: "Composition of Ervaj", bonus: 10, unit: "%", detail: "(Bard 60)" },
        { spell: "Melody of Ervaj", bonus: 5, unit: "%", detail: "(Bard 50)" },
    ],
  },
  {
    id: "hp-hit-points--primary",
    category: "Other Buffs",
    stat: "HP (Hit Points)",
    label: "Primary",
    members: [
        { spell: "Aegolism", bonus: 1100, detail: "(Cleric 60)" },
        { spell: "Protection of the Glades", bonus: 470, detail: "(Group) (Druid 60)" },
        { spell: "Heroic Bond", bonus: 400, detail: "(Group) (Cleric 52)" },
        { spell: "Heroism", bonus: 400, detail: "(Cleric 52)" },
        { spell: "Natureskin", bonus: 400, detail: "(Druid 57)" },
        { spell: "Fortitude", bonus: 345, detail: "(Cleric 55)" },
        { spell: "Resolution", bonus: 250, detail: "(Cleric 44, Paladin 60)" },
        { spell: "Skin Like Nature", bonus: 250, detail: "(Druid 49, Ranger 59)" },
        { spell: "Armor of Protection", bonus: 225, detail: "(Cleric 34)" },
        { spell: "Skin Like Diamond", bonus: 200, detail: "(Druid 39, Ranger 54)" },
        { spell: "Valor", bonus: 200, detail: "(Cleric 34, Paladin 49)" },
        { spell: "Bravery", bonus: 140, detail: "(Cleric 24)" },
        { spell: "Skin Like Steel", bonus: 100, detail: "(Druid 24, Ranger 39)" },
        { spell: "Skin Like Rock", bonus: 100, detail: "(Druid 14, Ranger 22)" },
        { spell: "Center", bonus: 95, detail: "(Cleric 9, Paladin 22)" },
        { spell: "Courage", bonus: 20, detail: "(Cleric 1, Paladin 9)" },
        { spell: "Skin Like Wood", bonus: 20, detail: "(Druid 1, Ranger 9)" },
        { spell: "Inner Fire", bonus: 20, detail: "(Shaman 1)" },
        { spell: "Symbol of Marzin", bonus: 700, detail: "(Cleric 54)" },
        { spell: "Symbol of Naltron", bonus: 525, detail: "(Cleric 44, Paladin 58)" },
        { spell: "Naltron's Mark", bonus: 446, detail: "(Group) (Cleric 58)" },
        { spell: "Symbol of Pinzarn", bonus: 307, detail: "(Cleric 34, Paladin 49)" },
        { spell: "Symbol of Ryltan", bonus: 158, detail: "(Cleric 24, Paladin 39)" },
        { spell: "Symbol of Transal", bonus: 73, detail: "(Cleric 14, Paladin 30)" },
    ],
  },
  {
    id: "hp-hit-points--shielding-talisman",
    category: "Other Buffs",
    stat: "HP (Hit Points)",
    label: "Shielding / Talisman",
    members: [
        { spell: "Focus of Spirit", bonus: 405, detail: "(Shaman 60)" },
        { spell: "Talisman of Kragg", bonus: 380, detail: "(Shaman 55)" },
        { spell: "Shield of the Magi", bonus: 250, detail: "(Self-only: Enchanter 54, Magician 54, Necromancer 54, Wizard 54)" },
        { spell: "Talisman of Altuna", bonus: 250, detail: "(Shaman 44)" },
        { spell: "Arch Shielding", bonus: 150, detail: "(Self-only: Enchanter 44, Magician 44, Necromancer 44, Wizard 44, Click: Tri-Plated Golden Hackle Hammer)" },
        { spell: "Talisman of Tnarg", bonus: 150, detail: "(Shaman 34)" },
        { spell: "Greater Shielding", bonus: 100, detail: "(Self-only: Enchanter 34, Magician 34, Necromancer 34, Wizard 34)" },
        { spell: "Major Shielding", bonus: 75, detail: "(Self-only: Enchanter 24, Magician 24, Necromancer 24, Wizard 24, Click: Blood Ember Breastplate, Proc: Stave of Shielding)" },
        { spell: "Shielding", bonus: 50, detail: "(Self-only: Enchanter 16, Magician 16, Necromancer 16, Wizard 16)" },
        { spell: "Lesser Shielding", bonus: 30, detail: "(Self-only: Enchanter 8, Magician 8, Necromancer 8, Wizard 8)" },
        { spell: "Minor Shielding", bonus: 10, detail: "(Self-only: Enchanter 1, Magician 1, Necromancer 1, Wizard 1)" },
    ],
  },
  {
    id: "hp-hit-points--strength",
    category: "Other Buffs",
    stat: "HP (Hit Points)",
    label: "Strength",
    members: [
        { spell: "Divine Strength", bonus: 200, detail: "(Paladin 60)" },
        { spell: "Divine Glory", bonus: 100, detail: "(Paladin 53)" },
        { spell: "Strength of Nature", bonus: 75, detail: "(Ranger 51)" },
    ],
  },
  {
    id: "hp-regeneration--slot-1",
    category: "Other Buffs",
    stat: "HP Regeneration",
    label: "Slot 1",
    members: [
        { spell: "Fungal Regrowth", bonus: 15, detail: "(Click: Fungi Covered Great Staff, Fungus Covered Great Staff)" },
        { spell: "Regrowth of the Grove", bonus: 15, detail: "(Group: Druid 58, Click: Hauberk of Harmony, Nature Walker's Chestguard, Rowyl's Chestguard of Nature, Woven Grass Chestguard)" },
        { spell: "Regrowth", bonus: 15, detail: "(Druid 54, Shaman 52)" },
        { spell: "Chloroplast", bonus: 10, detail: "(Druid 44, Shaman 39, Ranger 55, Click: Elder Spiritist's Breastplate, Consumable: Skull-engraved Coin)" },
        { spell: "Frostreaver's Blessing", bonus: 10, detail: "(Click: Ring of Dain Frostreaver IV)" },
        { spell: "Pack Chloroplast", bonus: 10, detail: "(Group: Druid 49)" },
        { spell: "Dulsehound", bonus: 6, detail: "(Consumable: Potion of Dulsehound)" },
        { spell: "Fiery Might", bonus: 5, detail: "(Click: Chestplate of Fiery Might)" },
        { spell: "Pack Regeneration", bonus: 5, detail: "(Group: Druid 39)" },
        { spell: "Regeneration", bonus: 5, detail: "(Druid 34, Shaman 24, Click: Spiroc Healer's Cloak, Consumable: Pliable Goo)" },
        { spell: "Calimony", bonus: -2, detail: "(Consumable: Potion of Stinging Wort)" },
    ],
  },
  {
    id: "hp-regeneration--slot-2",
    category: "Other Buffs",
    stat: "HP Regeneration",
    label: "Slot 2",
    members: [
        { spell: "Divine Purpose", bonus: 8, detail: "(Self-only: Paladin 39)" },
        { spell: "Phantom Armor", bonus: 5, detail: "(Self-only: Magician 52)" },
        { spell: "Phantom Plate", bonus: 3, detail: "(Self-only: Magician 44, Click: Shissar Guardian Staff)" },
        { spell: "Aura of Battle", bonus: 2, detail: "(Click: Fearsome Shield, Pauldrons of Ferocity)" },
        { spell: "Extended Regeneration", bonus: 2, detail: "(Consumable: Blood of the Dhampyre)" },
        { spell: "Form of the Great Bear", bonus: 2, detail: "(Self-only: Shaman 55)" },
        { spell: "Phantom Chain", bonus: 2, detail: "(Self-only: Magician 29)" },
        { spell: "Stalwart Regeneration", bonus: 2, detail: "(Consumable: Bark Potion)" },
        { spell: "Phantom Leather", bonus: 1, detail: "(Self-only: Magician 16)" },
    ],
  },
  {
    id: "hp-regeneration--slot-3-6",
    category: "Other Buffs",
    stat: "HP Regeneration",
    label: "Slot 3 & 6",
    members: [
        { spell: "Spirit of Oak", bonus: 13, detail: "(Self-only: Druid 59)" },
        { spell: "Treeform", bonus: 5, detail: "(Self-only: Druid 9, Click: Maple Leaf Mask)" },
        { spell: "Illusion: Troll", bonus: 1, detail: "(Self-only: Enchanter 20)" },
    ],
  },
  {
    id: "hp-regeneration--slot-4",
    category: "Other Buffs",
    stat: "HP Regeneration",
    label: "Slot 4",
    members: [
        { spell: "Rejuvenation", bonus: 40, detail: "(Consumable: Potion of Greater Rejuvenation)" },
        { spell: "Rejuvenation", bonus: 20, detail: "(Consumable: Potion of Rejuvenation)" },
        { spell: "Rejuvenation", bonus: 10, detail: "(Consumable: Potion of Lesser Rejuvenation)" },
        { spell: "Natureskin", bonus: 4, detail: "(Druid 57)" },
        { spell: "Skin Like Nature", bonus: 2, detail: "(Druid 49, Ranger 59, Click: Robe of the Spring)" },
    ],
  },
  {
    id: "hp-regeneration--layer-2-slot-1",
    category: "Other Buffs",
    stat: "HP Regeneration",
    label: "Layer 2, Slot 1",
    members: [
        { spell: "Hymn of Restoration", bonus: 13, detail: "(+36) (Group: Bard 6)" },
        { spell: "Cantata of Replenishment", bonus: 12, detail: "(+33) (Group: Bard 55)" },
        { spell: "Cantata of Soothing", bonus: 4, detail: "(+11) (Group: Bard 34)" },
    ],
  },
  {
    id: "hp-regeneration--layer-2-slot-3",
    category: "Other Buffs",
    stat: "HP Regeneration",
    label: "Layer 2, Slot 3",
    members: [
        { spell: "Niv's Melody of Preservation", bonus: 9, detail: "(+25) (Group: Bard 47, Click: Breath of Harmony)" },
        { spell: "Psalm of Mystic Shielding", bonus: 5, detail: "(+14) (Group: Bard 41)" },
    ],
  },
  {
    id: "hp-regeneration--worn",
    category: "Other Buffs",
    stat: "HP Regeneration",
    label: "Worn",
    members: [
        { spell: "Fungal Regrowth", bonus: 15, detail: "(Worn: Fungus Covered Scale Tunic, Shroud of Longevity)" },
        { spell: "Regeneration", bonus: 5, detail: "(Worn: Ceremonial Iksar Chestplate, Zlandicar's Heart)" },
        { spell: "Rubicite Aura", bonus: 3, detail: "(Worn: Rubicite Breastplate)" },
        { spell: "Aura of Battle", bonus: 2, detail: "/item (Worn: Belt of Dwarf Slaying, Belt of the Great Turtle, Boots of Deep Thought, Boots of Silent Striding, Chestplate of Vindication, Silver Mask of the Slayer, Spirit Wracked Cord)" },
    ],
  },
  {
    id: "mana--primary",
    category: "Other Buffs",
    stat: "Mana",
    label: "Primary",
    members: [
        { spell: "Gift of Brilliance", bonus: 150, detail: "(Enchanter 60)" },
        { spell: "Gift of Insight", bonus: 100, detail: "(Enchanter 55)" },
        { spell: "Gift of Magic", bonus: 50, detail: "(Enchanter 34)" },
    ],
  },
  {
    id: "mana-regeneration--protection-of-the-glades",
    category: "Other Buffs",
    stat: "Mana Regeneration",
    label: "Protection of the Glades",
    members: [
        { spell: "Protection of the Glades", bonus: 6, detail: "(Druid 60)" },
    ],
  },
  {
    id: "mana-regeneration--clarity",
    category: "Other Buffs",
    stat: "Mana Regeneration",
    label: "Clarity",
    members: [
        { spell: "Gift of Pure Thought", bonus: 11, detail: "(Group) (Enchanter 59)" },
        { spell: "Clarity II", bonus: 11, detail: "(Enchanter 54)" },
        { spell: "Boon of the Clear Mind", bonus: 7, detail: "(Group) (Enchanter 52)" },
        { spell: "Clarity", bonus: 7, detail: "(Enchanter 29)" },
        { spell: "Breeze", bonus: 2, detail: "(Enchanter 16)" },
    ],
  },
  {
    id: "mana-regeneration--gift",
    category: "Other Buffs",
    stat: "Mana Regeneration",
    label: "Gift",
    members: [
        { spell: "Mask of the Hunter", bonus: 3, detail: "(Self-only: Druid 60)" },
        { spell: "Gift of Brilliance", bonus: 2, detail: "(Enchanter 60)" },
        { spell: "Form of the Howler", bonus: 2, detail: "(Self-only: Druid 54)" },
        { spell: "Gift of Insight", bonus: 1, detail: "(Enchanter 55)" },
    ],
  },
  {
    id: "mana-regeneration--chorus",
    category: "Other Buffs",
    stat: "Mana Regeneration",
    label: "Chorus",
    members: [
        { spell: "Cassindra's Chorus of Clarity", bonus: 7, detail: "(+14) (Bard 32)" },
        { spell: "Cassindra's Chant of Clarity", bonus: 2, detail: "(Bard 20)" },
    ],
  },
  {
    id: "mana-regeneration--cantata",
    category: "Other Buffs",
    stat: "Mana Regeneration",
    label: "Cantata",
    members: [
        { spell: "Cantata of Replenishment", bonus: 13, detail: "(Bard 55)" },
        { spell: "Cantata of Soothing", bonus: 5, detail: "(Bard 34)" },
    ],
  },
  {
    id: "mana-regeneration--self-only",
    category: "Other Buffs",
    stat: "Mana Regeneration",
    label: "Self-Only",
    members: [
        { spell: "Barrier of Force", bonus: 3, detail: "(Click: Staff of the Four)" },
        { spell: "Manaskin", bonus: 1, detail: "(Necromancer 52, Wizard 52)" },
    ],
  },
  {
    id: "mana-regeneration--lich",
    category: "Other Buffs",
    stat: "Mana Regeneration",
    label: "Lich",
    members: [
        { spell: "Demi Lich", bonus: 31, detail: "(-48 HP) (Necromancer 60)" },
        { spell: "Arch Lich", bonus: 20, detail: "(-20 HP) (Necromancer 60)" },
        { spell: "Lich", bonus: 20, detail: "(-22 HP) (Necromancer 49)" },
        { spell: "Call of Bones", bonus: 8, detail: "(-10 HP) (Necromancer 34)" },
        { spell: "Allure of Death", bonus: 4, detail: "(-6 HP) (Necromancer 20)" },
        { spell: "Dark Pact", bonus: 2, detail: "(-2 HP) (Necromancer 8)" },
    ],
  },
  {
    id: "cold-resistance--primary",
    category: "Resistances",
    stat: "Cold Resistance",
    label: "Primary",
    members: [
        { spell: "Circle of Summer", bonus: 45, detail: "(Group) (Druid 52)" },
        { spell: "Resist Cold", bonus: 40, detail: "(Cleric 34, Druid 24, Ranger 49, Shaman 29)" },
        { spell: "Endure Cold", bonus: 20, detail: "(Cleric 9, Druid 1, Ranger 9, Shaman 5)" },
    ],
  },
  {
    id: "cold-resistance--flower-armor",
    category: "Resistances",
    stat: "Cold Resistance",
    label: "Flower/Armor",
    members: [
        { spell: "Elemental Armor", bonus: 30, detail: "(Magician 44, Wizard 44)" },
    ],
  },
  {
    id: "cold-resistance--bard",
    category: "Resistances",
    stat: "Cold Resistance",
    label: "Bard",
    members: [
        { spell: "Psalm of Warmth", bonus: 70, detail: "(+196) (Bard 25)" },
    ],
  },
  {
    id: "cold-resistance--potion",
    category: "Resistances",
    stat: "Cold Resistance",
    label: "Potion",
    members: [
        { spell: "Aura of Heat", bonus: 25, detail: "(Consumable: Greater Potion of Heat)" },
        { spell: "Aura of Heat", bonus: 15, detail: "(Consumable: Potion of Heat)" },
        { spell: "Aura of Heat", bonus: 5, detail: "(Consumable: Minor Potion of Heat)" },
    ],
  },
  {
    id: "disease-resistance--primary",
    category: "Resistances",
    stat: "Disease Resistance",
    label: "Primary",
    members: [
        { spell: "Aura of Black Petals", bonus: 50, detail: "(Click: Black Flower of Functionality)" },
        { spell: "Talisman of Jasinth", bonus: 45, detail: "(Group) (Shaman 51)" },
        { spell: "Resist Disease", bonus: 40, detail: "(Cleric 39, Druid 44, Necromancer 34, Paladin 51, Shaman 34)" },
        { spell: "Endure Disease", bonus: 20, detail: "(Cleric 14, Druid 19, Necromancer 12, Paladin 39, Shadow Knight 30, Shaman 9)" },
        { spell: "Resistant Skin", bonus: 15, detail: "(Self-only: Wizard 12)" },
    ],
  },
  {
    id: "disease-resistance--psalm",
    category: "Resistances",
    stat: "Disease Resistance",
    label: "Psalm",
    members: [
        { spell: "Psalm of Vitality", bonus: 70, detail: "(+196) (Bard 25)" },
    ],
  },
  {
    id: "disease-resistance--item",
    category: "Resistances",
    stat: "Disease Resistance",
    label: "Item",
    members: [
        { spell: "Aura of Antibody", bonus: 25, detail: "(Consumable: Greater Potion of Antibody)" },
        { spell: "Aloe Sweat", bonus: 15, detail: "(Self-Only Click:: Disciple Symbol of Tunare)" },
        { spell: "Aura of Antibody", bonus: 15, detail: "(Consumable: Potion of Antibody)" },
        { spell: "Aura of Antibody", bonus: 5, detail: "(Consumable: Minor Potion of Antibody)" },
    ],
  },
  {
    id: "fire-resistance--slot-1",
    category: "Resistances",
    stat: "Fire Resistance",
    label: "Slot 1",
    members: [
        { spell: "Aura of Red Petals", bonus: 50, detail: "(Click: Red Flower of Functionality)" },
        { spell: "Circle of Winter", bonus: 45, detail: "(Group: Druid 51)" },
        { spell: "Resist Fire", bonus: 40, detail: "(Cleric 34, Druid 24, Ranger 49, Shaman 29)" },
        { spell: "Endure Fire", bonus: 20, detail: "(Cleric 9, Druid 1, Ranger 9, Shaman 5)" },
    ],
  },
  {
    id: "fire-resistance--slot-2",
    category: "Resistances",
    stat: "Fire Resistance",
    label: "Slot 2",
    members: [
        { spell: "Aegis of Ro", bonus: 33, detail: "(Group: Magician 60)" },
        { spell: "Cadeau of Flame", bonus: 33, detail: "(Magician 56)" },
        { spell: "Boon of Immolation", bonus: 25, detail: "(Group: Magician 53)" },
        { spell: "Shield of Lava", bonus: 25, detail: "(Magician 49, Click: Arch Mage's Robe, Prestidigitator's Robe, Robe of Conjuration, Summoner's Robe, Consumable: Lava Diamond, Ro's Breath, Wand of Lava)" },
        { spell: "Barrier of Combustion", bonus: 22, detail: "(Magician 39)" },
        { spell: "Inferno Shield", bonus: 20, detail: "(Magician 29, Consumable: Lava Potion)" },
        { spell: "Shield of Flame", bonus: 15, detail: "(Magician 20, Click: Blazing Vambraces, Singing Steel Bracer, Charred Black Staff)" },
        { spell: "O'Keils Radiation", bonus: 10, detail: "(Wizard 4, Click: Boots of the Invoker, Icicle Boots, Sage's Boots, Sorcerer's Boots)" },
        { spell: "Shield of Fire", bonus: 10, detail: "(Magician 8)" },
    ],
  },
  {
    id: "fire-resistance--slot-3",
    category: "Resistances",
    stat: "Fire Resistance",
    label: "Slot 3",
    members: [
        { spell: "O'Keils Flickering Flame", bonus: 10, detail: "(Wizard 34)" },
    ],
  },
  {
    id: "fire-resistance--slot-4",
    category: "Resistances",
    stat: "Fire Resistance",
    label: "Slot 4",
    members: [
        { spell: "Elemental Armor", bonus: 30, detail: "(Self-Only: Magician 44, Wizard 44, Click: Icicle Pantaloons, Pants of the Invoker, Diamond Encrusted Staff, Sage's Pantaloons, Sorcerer's Pantaloons)" },
        { spell: "Aura of Cold", bonus: 25, detail: "(Consumable: Greater Potion of Cold)" },
        { spell: "Aura of Cold", bonus: 15, detail: "(Consumable: Potion of Cold)" },
        { spell: "Aura of Cold", bonus: 5, detail: "(Consumable: Minor Potion of Cold)" },
    ],
  },
  {
    id: "fire-resistance--layer-2-slot-2-3",
    category: "Resistances",
    stat: "Fire Resistance",
    label: "Layer 2, Slot 2 & 3",
    members: [
        { spell: "Psalm of Cooling", bonus: 70, detail: "(+196) (Bard 33)" },
        { spell: "Elemental Rhythms", bonus: 35, detail: "(+98) (Bard 9)" },
    ],
  },
  {
    id: "magic-resistance--primary",
    category: "Resistances",
    stat: "Magic Resistance",
    label: "Primary",
    members: [
        { spell: "Group Resist Magic", bonus: 55, detail: "(Group) (Enchanter 49, Cast)" },
        { spell: "Aura of Blue Petals", bonus: 50, detail: "(Click: Blue Flower of Functionality)" },
        { spell: "Resist Magic", bonus: 40, detail: "(Cleric 44, Druid 49 Enchanter 39, Paladin 55, Shaman 44)" },
        { spell: "Endure Magic", bonus: 20, detail: "(Cleric 19, Druid 34, Enchanter 20, Paladin 30, Shaman 19)" },
    ],
  },
  {
    id: "magic-resistance--psalm",
    category: "Resistances",
    stat: "Magic Resistance",
    label: "Psalm",
    members: [
        { spell: "Psalm of Mystic Shielding", bonus: 70, detail: "(+196) (Bard 41)" },
        { spell: "Elemental Rhythms", bonus: 35, detail: "(+98) (Bard 9)" },
        { spell: "Guardian Rhythms", bonus: 35, detail: "(+98) (Bard 9)" },
        { spell: "Purifying Rhythms", bonus: 35, detail: "(+98) (Bard 9)" },
    ],
  },
  {
    id: "magic-resistance--magic-shield",
    category: "Resistances",
    stat: "Magic Resistance",
    label: "Magic Shield",
    members: [
        { spell: "Shield of the Magi", bonus: 24, detail: "(Self-only: Enchanter 54, Magician 54, Necromancer 54, Wizard 54)" },
        { spell: "Arch Shielding", bonus: 20, detail: "(Self-only: Enchanter 44, Magician 44, Necromancer 44, Wizard 44)" },
        { spell: "Greater Shielding", bonus: 16, detail: "(Self-only: Enchanter 34, Magician 34, Necromancer 34, Wizard 34)" },
        { spell: "Major Shielding", bonus: 14, detail: "(Self-only: Enchanter 24, Magician 24, Necromancer 24, Wizard 24)" },
        { spell: "Shielding", bonus: 12, detail: "(Self-only: Enchanter 16, Magician 16, Necromancer 16, Wizard 16)" },
    ],
  },
  {
    id: "magic-resistance--potion",
    category: "Resistances",
    stat: "Magic Resistance",
    label: "Potion",
    members: [
        { spell: "Null Aura", bonus: 25, detail: "(Consumable: Greater Null Potion)" },
        { spell: "Null Aura", bonus: 15, detail: "(Consumable: Null Potion)" },
        { spell: "Null Aura", bonus: 5, detail: "(Consumable: Minor Null Potion)" },
    ],
  },
  {
    id: "poison-resistance--primary",
    category: "Resistances",
    stat: "Poison Resistance",
    label: "Primary",
    members: [
        { spell: "Talisman of Shadoo", bonus: 45, detail: "(Group) (Shaman 53)" },
        { spell: "Resist Poison", bonus: 40, detail: "(Cleric 34, Druid 44, Shaman 39)" },
        { spell: "Endure Poison", bonus: 20, detail: "(Cleric 9, Druid 19, Paladin 22, Shaman 14)" },
        { spell: "Resistant Skin", bonus: 15, detail: "(Self-only: Wizard 12)" },
    ],
  },
  {
    id: "poison-resistance--flower",
    category: "Resistances",
    stat: "Poison Resistance",
    label: "Flower",
    members: [
        { spell: "Aura of Green Petals", bonus: 50, detail: "(Click: Green Flower of Functionality)" },
    ],
  },
  {
    id: "poison-resistance--dead-man-floating",
    category: "Resistances",
    stat: "Poison Resistance",
    label: "Dead Man Floating",
    members: [
        { spell: "Dead Man Floating", bonus: 70, detail: "(Necromancer 44)" },
    ],
  },
  {
    id: "poison-resistance--psalm",
    category: "Resistances",
    stat: "Poison Resistance",
    label: "Psalm",
    members: [
        { spell: "Psalm of Purity", bonus: 70, detail: "(+196) (Bard 37)" },
    ],
  },
  {
    id: "poison-resistance--item",
    category: "Resistances",
    stat: "Poison Resistance",
    label: "Item",
    members: [
        { spell: "Aura of Purity", bonus: 25, detail: "(Consumable: Greater Potion of Purity)" },
        { spell: "Aloe Sweat", bonus: 15, detail: "(Self-Only Click:: Disciple Symbol of Tunare)" },
        { spell: "Aura of Purity", bonus: 15, detail: "(Consumable: Potion of Purity)" },
        { spell: "Aura of Purity", bonus: 5, detail: "(Consumable: Minor Potion of Purity)" },
    ],
  },
];
